// Advanced Problems — 25 problems (Real Interview + Complex Patterns)
export const advanced = [
    {
        id: 176,
        title: "Consecutive Login Days",
        category: "Advanced",
        difficulty: "hard",
        description: "[FAANG Classic] Find customers who placed orders on at least 2 consecutive days.\n\nTable: orders",
        hint: "Self join where order dates differ by 1 day.",
        solution: "SELECT DISTINCT o1.customer_id FROM orders o1 JOIN orders o2 ON o1.customer_id = o2.customer_id AND date(o1.order_date, '+1 day') = date(o2.order_date);",
    },
    {
        id: 177,
        title: "Department Budget Utilization",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon] Find each department's salary utilization as a percentage of its budget. Show department name, total salary, budget, and utilization %.\n\nTables: employees, departments",
        hint: "JOIN, GROUP BY, then calculate percentage.",
        solution: "SELECT d.name, SUM(e.salary) AS total_salary, d.budget, ROUND(SUM(e.salary) * 100.0 / d.budget, 2) AS utilization_pct FROM departments d LEFT JOIN employees e ON d.id = e.department_id GROUP BY d.id ORDER BY utilization_pct DESC;",
    },
    {
        id: 178,
        title: "Running Balance",
        category: "Advanced",
        difficulty: "hard",
        description: "[Google] Calculate the running balance for each account (credits add, debits subtract).\n\nTable: transactions",
        hint: "Use CASE WHEN for sign, then SUM OVER for running total.",
        solution: "SELECT id, account_id, type, amount, transaction_date, SUM(CASE WHEN type = 'credit' THEN amount ELSE -amount END) OVER (PARTITION BY account_id ORDER BY transaction_date, id) AS running_balance FROM transactions;",
    },
    {
        id: 179,
        title: "Market Basket Analysis",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon] Find pairs of products that are frequently bought together (by the same customer). Show product pairs and the count of customers who bought both.\n\nTables: orders, products",
        hint: "Self join orders where same customer bought different products.",
        solution: "SELECT p1.name AS product1, p2.name AS product2, COUNT(DISTINCT o1.customer_id) AS bought_together FROM orders o1 JOIN orders o2 ON o1.customer_id = o2.customer_id AND o1.product_id < o2.product_id JOIN products p1 ON o1.product_id = p1.id JOIN products p2 ON o2.product_id = p2.id GROUP BY o1.product_id, o2.product_id HAVING COUNT(DISTINCT o1.customer_id) >= 2 ORDER BY bought_together DESC;",
    },
    {
        id: 180,
        title: "Retention Analysis",
        category: "Advanced",
        difficulty: "hard",
        description: "[Meta] For each customer, determine if they're 'Retained' (ordered in both first and second half of 2023) or 'Churned' (only first half) or 'New' (only second half).\n\nTable: orders",
        hint: "Use CASE WHEN with MAX/MIN dates or conditional counts.",
        solution: "SELECT customer_id, CASE WHEN SUM(CASE WHEN order_date < '2023-07-01' THEN 1 ELSE 0 END) > 0 AND SUM(CASE WHEN order_date >= '2023-07-01' THEN 1 ELSE 0 END) > 0 THEN 'Retained' WHEN SUM(CASE WHEN order_date < '2023-07-01' THEN 1 ELSE 0 END) > 0 THEN 'Churned' ELSE 'New' END AS status FROM orders WHERE strftime('%Y', order_date) = '2023' GROUP BY customer_id;",
    },
    {
        id: 181,
        title: "Find the Team Size",
        category: "Advanced",
        difficulty: "easy",
        description: "[LeetCode 1303] Write a query to find the team size for each employee (count of employees in same department).\n\nTable: employees",
        hint: "Use a window function: COUNT(*) OVER (PARTITION BY department_id).",
        solution: "SELECT name, department_id, COUNT(*) OVER (PARTITION BY department_id) AS team_size FROM employees;",
    },
    {
        id: 182,
        title: "Consecutive Numbers",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 180] Find all numbers that appear at least 3 times consecutively. Use employee IDs: find employees where 3 consecutive IDs are in the same department.\n\nTable: employees",
        hint: "Self join e1, e2, e3 where IDs are consecutive.",
        solution: "SELECT DISTINCT e1.department_id FROM employees e1 JOIN employees e2 ON e2.id = e1.id + 1 JOIN employees e3 ON e3.id = e1.id + 2 WHERE e1.department_id = e2.department_id AND e2.department_id = e3.department_id;",
    },
    {
        id: 183,
        title: "Highest Salary in Each Department",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 185] Find employees who earn the top 3 salaries in each department.\n\nTables: employees, departments",
        hint: "DENSE_RANK PARTITION BY department ORDER BY salary DESC.",
        solution: "WITH ranked AS (SELECT e.name AS Employee, d.name AS Department, e.salary AS Salary, DENSE_RANK() OVER (PARTITION BY e.department_id ORDER BY e.salary DESC) AS rnk FROM employees e JOIN departments d ON e.department_id = d.id) SELECT Department, Employee, Salary FROM ranked WHERE rnk <= 3 ORDER BY Department, Salary DESC;",
    },
    {
        id: 184,
        title: "Customer Lifetime Value",
        category: "Advanced",
        difficulty: "hard",
        description: "[Google] Calculate CLV: total spending, number of orders, average order value, and days since first order for each customer.\n\nTables: customers, orders",
        hint: "Multiple aggregations in one query.",
        solution: "SELECT c.name, COUNT(o.id) AS total_orders, ROUND(SUM(o.amount), 2) AS total_spent, ROUND(AVG(o.amount), 2) AS avg_order_value, CAST(julianday('2024-03-01') - julianday(MIN(o.order_date)) AS INTEGER) AS days_since_first FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'completed' GROUP BY c.id ORDER BY total_spent DESC;",
    },
    {
        id: 185,
        title: "YoY Growth Rate",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon] Calculate the month-over-month growth rate of revenue.\n\nTable: orders",
        hint: "CTE for monthly revenue, then LAG for comparison.",
        solution: "WITH monthly AS (SELECT strftime('%Y-%m', order_date) AS month, SUM(amount) AS revenue FROM orders WHERE status = 'completed' GROUP BY month) SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev_month, CASE WHEN LAG(revenue) OVER (ORDER BY month) IS NOT NULL THEN ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0 / LAG(revenue) OVER (ORDER BY month), 2) END AS growth_pct FROM monthly;",
    },
    {
        id: 186,
        title: "Exchange Seats",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 626] Swap every two consecutive employee IDs. If number of employees is odd, last one stays.\n\nTable: employees",
        hint: "CASE WHEN id % 2 = 1 AND next exists THEN swap.",
        solution: "SELECT CASE WHEN id % 2 = 1 AND id + 1 <= (SELECT MAX(id) FROM employees) THEN id + 1 WHEN id % 2 = 0 THEN id - 1 ELSE id END AS id, name FROM employees ORDER BY id;",
    },
    {
        id: 187,
        title: "Friend Requests Acceptance Rate",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode variant] From orders, find the percentage of orders that were completed vs total orders. Also show cancelled and returned rates.\n\nTable: orders",
        hint: "COUNT with CASE WHEN divided by total COUNT.",
        solution: "SELECT ROUND(SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS completion_rate, ROUND(SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS cancellation_rate, ROUND(SUM(CASE WHEN status = 'returned' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS return_rate FROM orders;",
    },
    {
        id: 188,
        title: "Product Revenue Rank",
        category: "Advanced",
        difficulty: "medium",
        description: "[Microsoft] Rank products by total revenue and show cumulative revenue percentage.\n\nTables: orders, products",
        hint: "CTE for product revenue, then RANK and cumulative SUM.",
        solution: "WITH prod_rev AS (SELECT p.name, SUM(o.amount) AS revenue FROM orders o JOIN products p ON o.product_id = p.id WHERE o.status = 'completed' GROUP BY p.id) SELECT name, revenue, RANK() OVER (ORDER BY revenue DESC) AS revenue_rank, ROUND(SUM(revenue) OVER (ORDER BY revenue DESC) * 100.0 / SUM(revenue) OVER (), 2) AS cumulative_pct FROM prod_rev;",
    },
    {
        id: 189,
        title: "Active Users Analysis",
        category: "Advanced",
        difficulty: "hard",
        description: "[Meta] Find 'power customers' — those who ordered in at least 3 different months in 2023.\n\nTable: orders",
        hint: "COUNT DISTINCT months per customer HAVING >= 3.",
        solution: "SELECT customer_id, COUNT(DISTINCT strftime('%m', order_date)) AS active_months FROM orders WHERE strftime('%Y', order_date) = '2023' GROUP BY customer_id HAVING COUNT(DISTINCT strftime('%m', order_date)) >= 3;",
    },
    {
        id: 190,
        title: "Immediate vs Scheduled Orders",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 1174 variant] Find the percentage of first orders that are 'Electronics' category for each customer.\n\nTables: orders, products",
        hint: "Find first order per customer, check if product is Electronics.",
        solution: "WITH first_orders AS (SELECT customer_id, product_id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS rn FROM orders) SELECT ROUND(SUM(CASE WHEN p.category = 'Electronics' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS electronics_first_pct FROM first_orders f JOIN products p ON f.product_id = p.id WHERE f.rn = 1;",
    },
    {
        id: 191,
        title: "Managers with 2+ Reports",
        category: "Advanced",
        difficulty: "easy",
        description: "[LeetCode 570] Find all managers who have at least 2 direct reports.\n\nTable: employees",
        hint: "GROUP BY manager_id HAVING COUNT >= 2.",
        solution: "SELECT m.name AS manager FROM employees e JOIN employees m ON e.manager_id = m.id GROUP BY m.id HAVING COUNT(*) >= 2;",
    },
    {
        id: 192,
        title: "Tree Node Type",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 608] Classify each employee as 'Root' (no manager), 'Leaf' (not a manager of anyone), or 'Inner' (both has manager and is a manager).\n\nTable: employees",
        hint: "Use CASE WHEN with subquery checking manager_id.",
        solution: "SELECT id, name, CASE WHEN manager_id IS NULL THEN 'Root' WHEN id NOT IN (SELECT DISTINCT manager_id FROM employees WHERE manager_id IS NOT NULL) THEN 'Leaf' ELSE 'Inner' END AS node_type FROM employees;",
    },
    {
        id: 193,
        title: "Trips and Users Cancellation",
        category: "Advanced",
        difficulty: "hard",
        description: "[LeetCode 262 variant] Find the cancellation rate per month for orders. Show month and cancellation rate (cancelled orders / total orders).\n\nTable: orders",
        hint: "GROUP BY month, ratio of cancelled to total.",
        solution: "SELECT strftime('%Y-%m', order_date) AS month, ROUND(SUM(CASE WHEN status = 'cancelled' THEN 1.0 ELSE 0 END) / COUNT(*), 4) AS cancellation_rate FROM orders GROUP BY month ORDER BY month;",
    },
    {
        id: 194,
        title: "Human Traffic — Peak Days",
        category: "Advanced",
        difficulty: "hard",
        description: "[LeetCode 601 variant] Find dates where order count was >= 3 (busy days).\n\nTable: orders",
        hint: "GROUP BY order_date HAVING COUNT >= 3.",
        solution: "SELECT order_date, COUNT(*) AS order_count, SUM(amount) AS day_revenue FROM orders GROUP BY order_date HAVING COUNT(*) >= 3 ORDER BY order_count DESC;",
    },
    {
        id: 195,
        title: "Reclassify Products",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 1484 variant] Group products by category and list all product names as a comma-separated string.\n\nTable: products",
        hint: "Use GROUP_CONCAT() in SQLite.",
        solution: "SELECT category, GROUP_CONCAT(name, ', ') AS products FROM products GROUP BY category;",
    },
    {
        id: 196,
        title: "Islands of Data",
        category: "Advanced",
        difficulty: "hard",
        description: "[Google] Find 'islands' — groups of employees with consecutive IDs in the same department. Show department_id and the start/end of each island.\n\nTable: employees",
        hint: "Use ROW_NUMBER difference trick to identify groups.",
        solution: "WITH numbered AS (SELECT id, department_id, id - ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY id) AS grp FROM employees) SELECT department_id, MIN(id) AS island_start, MAX(id) AS island_end, COUNT(*) AS island_size FROM numbered GROUP BY department_id, grp HAVING COUNT(*) > 1 ORDER BY island_start;",
    },
    {
        id: 197,
        title: "Unpivot Data",
        category: "Advanced",
        difficulty: "hard",
        description: "Write a query to show each department's min, max, and avg salary as rows (unpivot-like). Each row should have: department_id, metric_name, metric_value.\n\nTable: employees",
        hint: "Use UNION ALL for each metric.",
        solution: "SELECT department_id, 'min_salary' AS metric, MIN(salary) AS value FROM employees GROUP BY department_id UNION ALL SELECT department_id, 'max_salary', MAX(salary) FROM employees GROUP BY department_id UNION ALL SELECT department_id, 'avg_salary', ROUND(AVG(salary), 2) FROM employees GROUP BY department_id ORDER BY department_id, metric;",
    },
    {
        id: 198,
        title: "Funnel Analysis",
        category: "Advanced",
        difficulty: "hard",
        description: "[Meta] Simulate a funnel: customers signed up → placed first order → placed 3+ orders. Show count at each stage.\n\nTables: customers, orders",
        hint: "Use subqueries for each funnel stage.",
        solution: "SELECT (SELECT COUNT(*) FROM customers) AS total_signups, (SELECT COUNT(DISTINCT customer_id) FROM orders) AS placed_order, (SELECT COUNT(*) FROM (SELECT customer_id FROM orders GROUP BY customer_id HAVING COUNT(*) >= 3)) AS three_plus_orders;",
    },
    {
        id: 199,
        title: "RFM Segmentation",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon] Perform RFM (Recency, Frequency, Monetary) analysis for customers. Show each customer's last order date, order count, and total spent.\n\nTables: customers, orders",
        hint: "GROUP by customer with MAX(date), COUNT, SUM.",
        solution: "SELECT c.name, MAX(o.order_date) AS last_order_date, COUNT(o.id) AS frequency, ROUND(SUM(o.amount), 2) AS monetary, CAST(julianday('2024-03-01') - julianday(MAX(o.order_date)) AS INTEGER) AS recency_days FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'completed' GROUP BY c.id ORDER BY monetary DESC;",
    },
    {
        id: 200,
        title: "Complete Business Report",
        category: "Advanced",
        difficulty: "hard",
        description: "[Final Boss] Write a comprehensive query showing: total customers, total orders, total revenue, avg order value, top category, best month, and highest spending customer — all in one result.\n\nTables: customers, orders, products",
        hint: "Use multiple scalar subqueries in one SELECT.",
        solution: "SELECT (SELECT COUNT(*) FROM customers) AS total_customers, (SELECT COUNT(*) FROM orders WHERE status = 'completed') AS total_orders, (SELECT ROUND(SUM(amount), 2) FROM orders WHERE status = 'completed') AS total_revenue, (SELECT ROUND(AVG(amount), 2) FROM orders WHERE status = 'completed') AS avg_order_value, (SELECT p.category FROM orders o JOIN products p ON o.product_id = p.id WHERE o.status = 'completed' GROUP BY p.category ORDER BY SUM(o.amount) DESC LIMIT 1) AS top_category, (SELECT strftime('%Y-%m', order_date) FROM orders WHERE status = 'completed' GROUP BY strftime('%Y-%m', order_date) ORDER BY SUM(amount) DESC LIMIT 1) AS best_month, (SELECT c.name FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'completed' GROUP BY c.id ORDER BY SUM(o.amount) DESC LIMIT 1) AS top_customer;",
    },
];
