// Advanced Problems — 25 FAANG Interview Questions (Real Interview + Complex Patterns)
export const advanced = [
    {
        id: 176,
        title: "Consecutive Login Days",
        category: "Advanced",
        difficulty: "hard",
        description: "[LeetCode 180 variant · Amazon · Google] Find employees whose salary appears at least 2 consecutive times in the salary history table (same employee, consecutive date ranges).\n\nTable: salaries\n\nConsecutive sequence detection — the 'Gaps and Islands' pattern. One of the hardest and most-asked FAANG patterns.",
        hint: "Use LAG to compare each salary with the previous one for the same employee.",
        solution: "SELECT DISTINCT s1.emp_id, s1.salary FROM salaries s1 JOIN salaries s2 ON s1.emp_id = s2.emp_id AND s1.salary = s2.salary AND s1.id <> s2.id;",
    },
    {
        id: 177,
        title: "Nth Highest Salary (Generic)",
        category: "Advanced",
        difficulty: "hard",
        description: "[LeetCode 177 · Amazon · Google · Meta] Write a query to find the 3rd highest DISTINCT salary. Return NULL if it doesn't exist.\n\nTable: employees\n\nThe Nth Highest Salary — the #1 most-asked SQL question at FAANG. Must handle the NULL edge case.",
        hint: "SELECT DISTINCT salary ORDER BY DESC LIMIT 1 OFFSET N-1, wrapped in an outer SELECT for NULL safety.",
        solution: "SELECT (SELECT DISTINCT salary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 2) AS ThirdHighestSalary;",
    },
    {
        id: 178,
        title: "Running Balance",
        category: "Advanced",
        difficulty: "hard",
        description: "[Goldman Sachs · Google] Calculate the running balance for each account. Credits add to balance, debits subtract.\n\nTable: transactions\n\nConditional running sum — combines CASE WHEN with window functions. A real banking interview question.",
        hint: "SUM(CASE WHEN type = 'credit' THEN amount ELSE -amount END) OVER (PARTITION BY account_id ORDER BY date).",
        solution: "SELECT account_id, date, type, amount, SUM(CASE WHEN type = 'credit' THEN amount ELSE -amount END) OVER (PARTITION BY account_id ORDER BY date) AS running_balance FROM transactions;",
    },
    {
        id: 179,
        title: "Department Team Size per Employee",
        category: "Advanced",
        difficulty: "medium",
        description: "[Amazon · Microsoft] Write a query to show each employee alongside the total size of their team (department count), without using a subquery or JOIN.\n\nTable: employees\n\nWindow function COUNT OVER for denormalization — adds group-level info to individual rows.",
        hint: "COUNT(*) OVER (PARTITION BY department_id) gives each row the team size.",
        solution: "SELECT name, department_id, COUNT(*) OVER (PARTITION BY department_id) AS team_size FROM employees;",
    },
    {
        id: 180,
        title: "Month-over-Month Retention",
        category: "Advanced",
        difficulty: "hard",
        description: "[Meta · Netflix] Write a query to find customers who placed orders in BOTH January and February 2023 (retained customers).\n\nTable: orders\n\nRetention analysis — finding users active in consecutive periods. A core product analytics question at Meta and Netflix.",
        hint: "INTERSECT or self-join: find customer_ids with orders in month 01 AND month 02.",
        solution: "SELECT DISTINCT o1.customer_id FROM orders o1 JOIN orders o2 ON o1.customer_id = o2.customer_id WHERE strftime('%Y-%m', o1.order_date) = '2023-01' AND strftime('%Y-%m', o2.order_date) = '2023-02';",
    },
    {
        id: 181,
        title: "Managers with 2+ Reports",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 570 · Amazon · Meta] Write a query to find all managers who have at least 2 direct reports. Show the manager's name.\n\nTable: employees\n\nLeetCode 570 — a commonly asked organizational hierarchy question. Uses GROUP BY on manager_id.",
        hint: "JOIN employees with themselves, GROUP BY manager, HAVING COUNT >= 2.",
        solution: "SELECT m.name AS manager FROM employees e JOIN employees m ON e.manager_id = m.id GROUP BY m.id HAVING COUNT(*) >= 2;",
    },
    {
        id: 182,
        title: "Monthly Cancellation Rate",
        category: "Advanced",
        difficulty: "medium",
        description: "[Uber · Amazon] Write a query to calculate the monthly order cancellation rate (cancelled orders / total orders). Show as a decimal rounded to 4 places.\n\nTable: orders\n\nRate calculation with conditional aggregation — a core business metrics question.",
        hint: "SUM(CASE WHEN cancelled) / COUNT(*) per month.",
        solution: "SELECT strftime('%Y-%m', order_date) AS month, ROUND(SUM(CASE WHEN status = 'cancelled' THEN 1.0 ELSE 0 END) / COUNT(*), 4) AS cancellation_rate FROM orders GROUP BY month ORDER BY month;",
    },
    {
        id: 183,
        title: "Customers Active 3+ Months",
        category: "Advanced",
        difficulty: "medium",
        description: "[Amazon · Netflix] Find customers who placed orders in at least 3 different months during 2023.\n\nTable: orders\n\nActive user analysis — COUNT(DISTINCT month) is a key engagement metric.",
        hint: "COUNT(DISTINCT strftime('%m', order_date)) with GROUP BY customer_id, HAVING >= 3.",
        solution: "SELECT customer_id, COUNT(DISTINCT strftime('%m', order_date)) AS active_months FROM orders WHERE strftime('%Y', order_date) = '2023' GROUP BY customer_id HAVING COUNT(DISTINCT strftime('%m', order_date)) >= 3;",
    },
    {
        id: 184,
        title: "Customer Lifetime Value (CLV)",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon · Stripe] Write a comprehensive CLV query: show each customer's name, total orders, total spending, average order value, and days since first order. Rank by total spending.\n\nTables: customers, orders\n\nCLV is a top business analytics question — combines multiple aggregations, JOINs, and date calculations.",
        hint: "LEFT JOIN customers with orders, compute COUNT, SUM, AVG, and date diff.",
        solution: "SELECT c.name, COUNT(o.id) AS total_orders, COALESCE(SUM(o.amount), 0) AS total_spent, COALESCE(ROUND(AVG(o.amount), 2), 0) AS avg_order_value, CAST(julianday('2024-03-01') - julianday(MIN(o.order_date)) AS INTEGER) AS days_since_first, DENSE_RANK() OVER (ORDER BY COALESCE(SUM(o.amount), 0) DESC) AS spend_rank FROM customers c LEFT JOIN orders o ON c.id = o.customer_id AND o.status = 'completed' GROUP BY c.id, c.name;",
    },
    {
        id: 185,
        title: "Product Revenue Rank with Cumulative %",
        category: "Advanced",
        difficulty: "hard",
        description: "[Microsoft · Amazon] Rank products by total revenue and show cumulative revenue percentage (Pareto analysis). Which products make up 80% of revenue?\n\nTables: orders, products\n\nPareto/ABC analysis — a real-world business intelligence question. Combines window functions and percentage calculations.",
        hint: "SUM revenue per product, RANK, then cumulative SUM / total SUM for percentage.",
        solution: "SELECT p.name, SUM(o.amount) AS revenue, DENSE_RANK() OVER (ORDER BY SUM(o.amount) DESC) AS rev_rank, ROUND(SUM(SUM(o.amount)) OVER (ORDER BY SUM(o.amount) DESC) * 100.0 / SUM(SUM(o.amount)) OVER (), 2) AS cumulative_pct FROM orders o JOIN products p ON o.product_id = p.id WHERE o.status = 'completed' GROUP BY p.id ORDER BY revenue DESC;",
    },
    {
        id: 186,
        title: "Busy Order Days",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 601 variant · Amazon] Find dates where the order count was >= 3 (peak traffic days).\n\nTable: orders\n\nPattern from LeetCode 601 'Human Traffic of Stadium' — finding dates meeting a threshold.",
        hint: "GROUP BY order_date, HAVING COUNT >= 3.",
        solution: "SELECT order_date, COUNT(*) AS order_count FROM orders GROUP BY order_date HAVING COUNT(*) >= 3 ORDER BY order_date;",
    },
    {
        id: 187,
        title: "STRING_AGG / GROUP_CONCAT",
        category: "Advanced",
        difficulty: "medium",
        description: "[Google · Microsoft] Write a query to show each product category with all product names concatenated into a single comma-separated string.\n\nTable: products\n\nGROUP_CONCAT (SQLite) / STRING_AGG (PostgreSQL/SQL Server) — string aggregation is tested at data-focused companies.",
        hint: "Use GROUP_CONCAT(name, ', ') with GROUP BY category.",
        solution: "SELECT category, GROUP_CONCAT(name, ', ') AS products FROM products GROUP BY category;",
    },
    {
        id: 188,
        title: "Islands of Consecutive IDs",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon · Google] Write a query to find 'islands' (consecutive groups) of employee IDs. Show the start and end ID of each island.\n\nTable: employees\n\nThe classic 'Gaps and Islands' problem — one of the hardest SQL patterns. Uses ROW_NUMBER to detect breaks in sequences.",
        hint: "id - ROW_NUMBER() gives a constant for each consecutive group. GROUP BY that constant.",
        solution: "SELECT MIN(id) AS island_start, MAX(id) AS island_end, COUNT(*) AS island_size FROM (SELECT id, id - ROW_NUMBER() OVER (ORDER BY id) AS grp FROM employees) grouped GROUP BY grp ORDER BY island_start;",
    },
    {
        id: 189,
        title: "Funnel Analysis — Order Pipeline",
        category: "Advanced",
        difficulty: "hard",
        description: "[Meta · Uber] Write a funnel analysis query: show total orders, completed orders, and the completion rate.\n\nTable: orders\n\nFunnel/conversion analysis — a staple at product-focused companies like Meta and Uber.",
        hint: "COUNT total, COUNT completed (with CASE or filter), then divide for rate.",
        solution: "SELECT COUNT(*) AS total_orders, SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed, SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled, SUM(CASE WHEN status = 'returned' THEN 1 ELSE 0 END) AS returned, ROUND(SUM(CASE WHEN status = 'completed' THEN 1.0 ELSE 0 END) / COUNT(*), 4) AS completion_rate FROM orders;",
    },
    {
        id: 190,
        title: "Year-over-Year Growth",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon · Netflix · Google] Write a query to calculate year-over-year revenue growth percentage.\n\nTable: orders\n\nYoY comparison using LAG — one of the most important time-series analytics patterns.",
        hint: "CTE for yearly revenue, then LAG to get previous year, compute % change.",
        solution: "WITH yearly AS (SELECT strftime('%Y', order_date) AS year, SUM(amount) AS revenue FROM orders WHERE status = 'completed' GROUP BY year) SELECT year, revenue, LAG(revenue) OVER (ORDER BY year) AS prev_year, ROUND((revenue - LAG(revenue) OVER (ORDER BY year)) * 100.0 / LAG(revenue) OVER (ORDER BY year), 2) AS yoy_growth_pct FROM yearly;",
    },
    {
        id: 191,
        title: "Salary Percentile per Department",
        category: "Advanced",
        difficulty: "hard",
        description: "[Goldman Sachs · Google] Write a query to show each employee's salary percentile within their department (what % of employees earn less than them).\n\nTable: employees\n\nPercentile/rank within group — PERCENT_RANK equivalent using window functions.",
        hint: "Count employees earning less in the same dept, divide by total - 1.",
        solution: "SELECT name, department_id, salary, ROUND(PERCENT_RANK() OVER (PARTITION BY department_id ORDER BY salary) * 100, 2) AS percentile FROM employees;",
    },
    {
        id: 192,
        title: "Pivot — Monthly Revenue Columns",
        category: "Advanced",
        difficulty: "hard",
        description: "[LeetCode 1179 · Amazon] Write a query to pivot monthly revenue into columns: show Jan, Feb, Mar as separate columns for 2023.\n\nTable: orders\n\nLeetCode 1179 'Reformat Department Table' pattern — manual pivoting with CASE WHEN. No PIVOT keyword in SQLite.",
        hint: "SUM(CASE WHEN month = '01' THEN amount END) AS Jan, etc.",
        solution: "SELECT SUM(CASE WHEN strftime('%m', order_date) = '01' THEN amount ELSE 0 END) AS Jan, SUM(CASE WHEN strftime('%m', order_date) = '02' THEN amount ELSE 0 END) AS Feb, SUM(CASE WHEN strftime('%m', order_date) = '03' THEN amount ELSE 0 END) AS Mar FROM orders WHERE strftime('%Y', order_date) = '2023' AND status = 'completed';",
    },
    {
        id: 193,
        title: "Self-Join — Salary Twins",
        category: "Advanced",
        difficulty: "medium",
        description: "[Meta · Google] Find all pairs of employees in DIFFERENT departments who earn exactly the same salary. Show both names, their departments, and salary.\n\nTable: employees\n\nSelf-join with multiple conditions — tests nuanced join logic.",
        hint: "Self-join on salary, add e1.department_id != e2.department_id, and e1.id < e2.id.",
        solution: "SELECT e1.name AS emp1, e1.department_id AS dept1, e2.name AS emp2, e2.department_id AS dept2, e1.salary FROM employees e1 JOIN employees e2 ON e1.salary = e2.salary AND e1.department_id != e2.department_id AND e1.id < e2.id;",
    },
    {
        id: 194,
        title: "Customer Purchase Frequency Distribution",
        category: "Advanced",
        difficulty: "hard",
        description: "[Meta · Uber] Create a histogram: how many customers made exactly 1 order, 2 orders, 3 orders, etc.?\n\nTable: orders\n\nHistogram / frequency distribution — 'Write a query to create a histogram' is a famous Meta interview question.",
        hint: "Subquery for orders per customer, then GROUP BY that count.",
        solution: "SELECT order_count, COUNT(*) AS num_customers FROM (SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id) counts GROUP BY order_count ORDER BY order_count;",
    },
    {
        id: 195,
        title: "Moving Sum — 7-Day Revenue",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon · Netflix] Calculate the 7-day rolling revenue sum for completed orders.\n\nTable: orders\n\nRolling window with ROWS BETWEEN — a time-series analytics pattern for dashboards and reporting.",
        hint: "SUM(amount) OVER (ORDER BY order_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW).",
        solution: "SELECT order_date, amount, SUM(amount) OVER (ORDER BY order_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7day_revenue FROM orders WHERE status = 'completed';",
    },
    {
        id: 196,
        title: "RFM Analysis",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon · Stripe] Perform simplified RFM (Recency, Frequency, Monetary) analysis: for each customer show days since last order, order count, and total spent. Score each dimension 1-3 using NTILE.\n\nTables: customers, orders\n\nRFM segmentation is the gold standard of customer analytics — frequently asked in data science interviews.",
        hint: "CTE for R/F/M metrics, then NTILE(3) for scoring each dimension.",
        solution: "WITH rfm AS (SELECT c.name, CAST(julianday('2024-03-01') - julianday(MAX(o.order_date)) AS INTEGER) AS recency, COUNT(o.id) AS frequency, SUM(o.amount) AS monetary FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'completed' GROUP BY c.id) SELECT name, recency, frequency, monetary, NTILE(3) OVER (ORDER BY recency DESC) AS r_score, NTILE(3) OVER (ORDER BY frequency) AS f_score, NTILE(3) OVER (ORDER BY monetary) AS m_score FROM rfm;",
    },
    {
        id: 197,
        title: "Dense Rank with Ties — Department Report",
        category: "Advanced",
        difficulty: "medium",
        description: "[Google · Amazon] Write a complete department performance report: department name, total employees, avg salary, total salary, and rank departments by average salary (handle ties).\n\nTables: employees, departments\n\nComprehensive reporting query — combines JOINs, aggregation, and window functions in one query.",
        hint: "JOIN + GROUP BY + DENSE_RANK() OVER (ORDER BY AVG DESC).",
        solution: "SELECT d.name, COUNT(e.id) AS emp_count, ROUND(AVG(e.salary), 2) AS avg_salary, SUM(e.salary) AS total_salary, DENSE_RANK() OVER (ORDER BY AVG(e.salary) DESC) AS salary_rank FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id;",
    },
    {
        id: 198,
        title: "Correlated DELETE Candidates",
        category: "Advanced",
        difficulty: "medium",
        description: "[LeetCode 196 · Meta] Write a SELECT to identify all duplicate email rows that would be deleted — keeping only the row with the lowest id per email.\n\nTable: employees\n\nThe SELECT version of LeetCode 196 'Delete Duplicate Emails'. Understanding this is essential before attempting the DELETE.",
        hint: "WHERE id > (SELECT MIN(id) FROM employees e2 WHERE e2.email = e.email) finds all non-minimum duplicates.",
        solution: "SELECT * FROM employees e WHERE id > (SELECT MIN(id) FROM employees e2 WHERE e2.email = e.email);",
    },
    {
        id: 199,
        title: "A/B Revenue Comparison",
        category: "Advanced",
        difficulty: "medium",
        description: "[Uber · Amazon] Compare revenue performance between two product categories: 'Electronics' vs 'Clothing'. Show total revenue, avg order value, and order count for each.\n\nTables: orders, products\n\nA/B testing analysis — comparing two segments side-by-side is a core data analyst skill.",
        hint: "Filter for the two categories, GROUP BY category, compute metrics.",
        solution: "SELECT p.category, COUNT(o.id) AS order_count, SUM(o.amount) AS total_revenue, ROUND(AVG(o.amount), 2) AS avg_order_value FROM orders o JOIN products p ON o.product_id = p.id WHERE o.status = 'completed' AND p.category IN ('Electronics', 'Clothing') GROUP BY p.category;",
    },
    {
        id: 200,
        title: "Complete Business Dashboard",
        category: "Advanced",
        difficulty: "hard",
        description: "[Amazon · Google · Meta] Build a comprehensive business dashboard in a single query: total revenue, total orders, unique customers, avg order value, best-selling product, and top customer. Use CTEs to organize.\n\nTables: orders, customers, products\n\nThe ultimate interview question — combines everything you've learned: CTEs, JOINs, aggregation, subqueries, and window functions.",
        hint: "Use multiple CTEs: one for overall metrics, one for top product, one for top customer.",
        solution: "WITH metrics AS (SELECT COUNT(*) AS total_orders, COUNT(DISTINCT customer_id) AS unique_customers, SUM(amount) AS total_revenue, ROUND(AVG(amount), 2) AS avg_order_value FROM orders WHERE status = 'completed'), top_product AS (SELECT p.name FROM orders o JOIN products p ON o.product_id = p.id WHERE o.status = 'completed' GROUP BY p.id ORDER BY SUM(o.amount) DESC LIMIT 1), top_customer AS (SELECT c.name FROM orders o JOIN customers c ON o.customer_id = c.id WHERE o.status = 'completed' GROUP BY c.id ORDER BY SUM(o.amount) DESC LIMIT 1) SELECT m.*, tp.name AS best_product, tc.name AS top_customer FROM metrics m, top_product tp, top_customer tc;",
    },
];
