// CASE WHEN + Conditional Logic — 15 problems
export const caseWhen = [
    {
        id: 161,
        title: "Salary Grade",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "Write a query to classify each employee's salary as 'High' (>90000), 'Medium' (70000-90000), or 'Low' (<70000).\n\nTable: employees",
        hint: "Use CASE WHEN with multiple conditions.",
        solution: "SELECT name, salary, CASE WHEN salary > 90000 THEN 'High' WHEN salary >= 70000 THEN 'Medium' ELSE 'Low' END AS salary_grade FROM employees;",
    },
    {
        id: 162,
        title: "Order Status Summary",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "Write a query to count orders by their status (completed, cancelled, returned).\n\nTable: orders",
        hint: "Use SUM(CASE WHEN status = '...' THEN 1 ELSE 0 END).",
        solution: "SELECT SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed, SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled, SUM(CASE WHEN status = 'returned' THEN 1 ELSE 0 END) AS returned FROM orders;",
    },
    {
        id: 163,
        title: "Student Grade Letter",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "Write a query to assign letter grades based on score: A (>=90), B (>=80), C (>=70), D (>=60), F (<60).\n\nTable: students",
        hint: "CASE WHEN score >= 90 THEN 'A' ...",
        solution: "SELECT name, score, CASE WHEN score >= 90 THEN 'A' WHEN score >= 80 THEN 'B' WHEN score >= 70 THEN 'C' WHEN score >= 60 THEN 'D' ELSE 'F' END AS letter_grade FROM students;",
    },
    {
        id: 164,
        title: "Conditional Aggregation",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "Write a query to show each department's count of high earners (>85000) and low earners (<=85000).\n\nTable: employees",
        hint: "SUM(CASE WHEN salary > 85000 ...) GROUP BY department.",
        solution: "SELECT department_id, SUM(CASE WHEN salary > 85000 THEN 1 ELSE 0 END) AS high_earners, SUM(CASE WHEN salary <= 85000 THEN 1 ELSE 0 END) AS low_earners FROM employees GROUP BY department_id;",
    },
    {
        id: 165,
        title: "Swap Salary",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "[LeetCode 627] Write a query that swaps all 'credit' to 'debit' and 'debit' to 'credit' in transactions.\n\nTable: transactions",
        hint: "CASE WHEN type = 'credit' THEN 'debit' ELSE 'credit'.",
        solution: "SELECT id, account_id, CASE WHEN type = 'credit' THEN 'debit' ELSE 'credit' END AS swapped_type, amount FROM transactions;",
    },
    {
        id: 166,
        title: "Age Groups",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "Classify employees into age groups: 'Young' (<30), 'Mid' (30-40), 'Senior' (>40).\n\nTable: employees",
        hint: "CASE WHEN age < 30 THEN 'Young' ...",
        solution: "SELECT name, age, CASE WHEN age < 30 THEN 'Young' WHEN age <= 40 THEN 'Mid' ELSE 'Senior' END AS age_group FROM employees;",
    },
    {
        id: 167,
        title: "Revenue Category",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "Classify each order as 'Small' (<50), 'Medium' (50-500), or 'Large' (>500) based on amount.\n\nTable: orders",
        hint: "CASE WHEN on amount ranges.",
        solution: "SELECT id, amount, CASE WHEN amount < 50 THEN 'Small' WHEN amount <= 500 THEN 'Medium' ELSE 'Large' END AS order_size FROM orders;",
    },
    {
        id: 168,
        title: "Conditional Join Result",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "Write a query to show employees with a label: 'Manager' if they manage someone, 'Individual Contributor' otherwise.\n\nTable: employees",
        hint: "Check if employee id exists in manager_id column.",
        solution: "SELECT e.name, CASE WHEN e.id IN (SELECT DISTINCT manager_id FROM employees WHERE manager_id IS NOT NULL) THEN 'Manager' ELSE 'Individual Contributor' END AS role_type FROM employees e;",
    },
    {
        id: 169,
        title: "Pivot — Department Salaries",
        category: "CASE WHEN",
        difficulty: "hard",
        description: "Write a query to show average salaries as columns for each city (pivot-like).\n\nTable: employees",
        hint: "Use AVG(CASE WHEN city = '...' THEN salary END) for each city.",
        solution: "SELECT ROUND(AVG(CASE WHEN city = 'New York' THEN salary END), 0) AS new_york, ROUND(AVG(CASE WHEN city = 'San Francisco' THEN salary END), 0) AS san_francisco, ROUND(AVG(CASE WHEN city = 'Chicago' THEN salary END), 0) AS chicago, ROUND(AVG(CASE WHEN city = 'Boston' THEN salary END), 0) AS boston, ROUND(AVG(CASE WHEN city = 'Seattle' THEN salary END), 0) AS seattle FROM employees;",
    },
    {
        id: 170,
        title: "Stock Alert Level",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "Classify products: 'Critical' (stock < 50), 'Low' (50-100), 'Normal' (>100).\n\nTable: products",
        hint: "CASE WHEN stock < 50 ...",
        solution: "SELECT name, stock, CASE WHEN stock < 50 THEN 'Critical' WHEN stock <= 100 THEN 'Low' ELSE 'Normal' END AS stock_level FROM products;",
    },
    {
        id: 171,
        title: "Transaction Balance",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "Write a query to show account balances by treating credits as positive and debits as negative.\n\nTable: transactions",
        hint: "SUM(CASE WHEN type = 'credit' THEN amount ELSE -amount END).",
        solution: "SELECT account_id, SUM(CASE WHEN type = 'credit' THEN amount ELSE -amount END) AS balance FROM transactions GROUP BY account_id;",
    },
    {
        id: 172,
        title: "Bonus Calculation",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[LeetCode 1873] Write a query to calculate bonus for employees: 10% if name doesn't start with 'M' and id is odd, 0 otherwise.\n\nTable: employees",
        hint: "CASE WHEN id % 2 = 1 AND name NOT LIKE 'M%'.",
        solution: "SELECT name, salary, CASE WHEN id % 2 = 1 AND name NOT LIKE 'M%' THEN ROUND(salary * 0.1, 2) ELSE 0 END AS bonus FROM employees;",
    },
    {
        id: 173,
        title: "Dynamic Pricing",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "Write a query to apply discounts: Electronics get 10% off, Books get 20% off, others no discount.\n\nTable: products",
        hint: "CASE WHEN category = 'Electronics' THEN price * 0.9 ...",
        solution: "SELECT name, category, price AS original_price, CASE WHEN category = 'Electronics' THEN ROUND(price * 0.9, 2) WHEN category = 'Books' THEN ROUND(price * 0.8, 2) ELSE price END AS discounted_price FROM products;",
    },
    {
        id: 174,
        title: "Customer Segment",
        category: "CASE WHEN",
        difficulty: "hard",
        description: "Segment customers based on their total spending: 'Premium' (>$2000), 'Regular' ($500-2000), 'New' (<$500). Include customers who never ordered as 'Inactive'.\n\nTables: customers, orders",
        hint: "LEFT JOIN, SUM, then CASE WHEN on total.",
        solution: "SELECT c.name, COALESCE(SUM(o.amount), 0) AS total_spent, CASE WHEN COALESCE(SUM(o.amount), 0) > 2000 THEN 'Premium' WHEN COALESCE(SUM(o.amount), 0) >= 500 THEN 'Regular' WHEN COALESCE(SUM(o.amount), 0) > 0 THEN 'New' ELSE 'Inactive' END AS segment FROM customers c LEFT JOIN orders o ON c.id = o.customer_id AND o.status = 'completed' GROUP BY c.id ORDER BY total_spent DESC;",
    },
    {
        id: 175,
        title: "Enrollment Status Report",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "For each course, show: total enrolled, count of A grades, count of B grades, count of C grades.\n\nTables: courses, enrollments",
        hint: "Use SUM(CASE WHEN grade = 'A'...) for each grade.",
        solution: "SELECT c.name AS course, COUNT(*) AS total, SUM(CASE WHEN e.grade = 'A' THEN 1 ELSE 0 END) AS a_count, SUM(CASE WHEN e.grade = 'B' THEN 1 ELSE 0 END) AS b_count, SUM(CASE WHEN e.grade = 'C' THEN 1 ELSE 0 END) AS c_count FROM courses c JOIN enrollments e ON c.id = e.course_id GROUP BY c.id;",
    },
];
