// CASE WHEN + Conditional Logic — 15 FAANG Interview Questions
export const caseWhen = [
    {
        id: 161,
        title: "Salary Grade Classification",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "[Amazon · Google] Write a query to classify each employee's salary: 'Senior' (>$90K), 'Mid' ($70K-$90K), 'Junior' (<$70K).\n\nTable: employees\n\nBasic CASE WHEN — the most fundamental conditional logic pattern in SQL interviews.",
        hint: "Use CASE WHEN salary > 90000 THEN 'Senior' WHEN salary >= 70000 THEN 'Mid' ELSE 'Junior' END.",
        solution: "SELECT name, salary, CASE WHEN salary > 90000 THEN 'Senior' WHEN salary >= 70000 THEN 'Mid' ELSE 'Junior' END AS grade FROM employees;",
    },
    {
        id: 162,
        title: "Pivot Order Status Counts",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Amazon · Meta] Write a query to pivot order statuses into columns: show counts of completed, cancelled, and returned orders in a single row.\n\nTable: orders\n\nSUM(CASE WHEN) for pivoting — the SQL way to transform rows into columns. A top FAANG pattern.",
        hint: "Use SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) for each status.",
        solution: "SELECT SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed, SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled, SUM(CASE WHEN status = 'returned' THEN 1 ELSE 0 END) AS returned FROM orders;",
    },
    {
        id: 163,
        title: "Conditional Aggregation per Department",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Google · Goldman Sachs] Write a query to show for each department: count of high earners (>$85K) and low earners (≤$85K) side by side.\n\nTable: employees\n\nCASE WHEN inside aggregate + GROUP BY — the most powerful reporting technique in SQL.",
        hint: "SUM(CASE WHEN salary > 85000 THEN 1 ELSE 0 END) with GROUP BY department_id.",
        solution: "SELECT department_id, SUM(CASE WHEN salary > 85000 THEN 1 ELSE 0 END) AS high_earners, SUM(CASE WHEN salary <= 85000 THEN 1 ELSE 0 END) AS low_earners FROM employees GROUP BY department_id;",
    },
    {
        id: 164,
        title: "Swap Salary (Gender Swap)",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "[LeetCode 627 · Amazon] Write a SELECT query to swap city values: if an employee is in 'New York', change to 'Seattle' and vice versa. Leave others unchanged.\n\nTable: employees\n\nLeetCode 627 'Swap Salary' pattern — CASE WHEN for value swapping. Originally tests UPDATE, but SELECT version for practice.",
        hint: "CASE WHEN city = 'New York' THEN 'Seattle' WHEN city = 'Seattle' THEN 'New York' ELSE city END.",
        solution: "SELECT name, CASE WHEN city = 'New York' THEN 'Seattle' WHEN city = 'Seattle' THEN 'New York' ELSE city END AS swapped_city FROM employees;",
    },
    {
        id: 165,
        title: "Order Size Classification",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "[Amazon · Flipkart] Write a query to classify each order as 'Small' (<$50), 'Medium' ($50-$500), or 'Large' (>$500) based on amount.\n\nTable: orders\n\nRange-based CASE WHEN — a very practical business classification pattern.",
        hint: "CASE WHEN amount < 50 THEN 'Small' WHEN amount <= 500 THEN 'Medium' ELSE 'Large' END.",
        solution: "SELECT id, amount, CASE WHEN amount < 50 THEN 'Small' WHEN amount <= 500 THEN 'Medium' ELSE 'Large' END AS order_size FROM orders;",
    },
    {
        id: 166,
        title: "Tree Node Classification",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[LeetCode 608 · Amazon · Google] Write a query to classify each employee as a 'Root' (no manager), 'Leaf' (not a manager of anyone), or 'Inner' (has a manager AND manages someone).\n\nTable: employees\n\nLeetCode 608 'Tree Node' — a frequently asked FAANG problem. Uses CASE with subqueries to classify nodes in a tree.",
        hint: "Root: manager_id IS NULL. Leaf: id NOT IN (SELECT manager_id...). Inner: everything else.",
        solution: "SELECT id, name, CASE WHEN manager_id IS NULL THEN 'Root' WHEN id NOT IN (SELECT DISTINCT manager_id FROM employees WHERE manager_id IS NOT NULL) THEN 'Leaf' ELSE 'Inner' END AS node_type FROM employees;",
    },
    {
        id: 167,
        title: "Stock Alert Levels",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "[Amazon · Walmart] Classify products: 'Critical' (stock < 50), 'Low' (50-100), 'Normal' (>100).\n\nTable: products\n\nCASE WHEN with business logic — a practical inventory management question.",
        hint: "CASE WHEN stock < 50 THEN 'Critical' WHEN stock <= 100 THEN 'Low' ELSE 'Normal' END.",
        solution: "SELECT name, stock, CASE WHEN stock < 50 THEN 'Critical' WHEN stock <= 100 THEN 'Low' ELSE 'Normal' END AS alert_level FROM products;",
    },
    {
        id: 168,
        title: "Department Budget Status",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Goldman Sachs · Microsoft] Write a query to classify each department's budget utilization: compare total employee salary vs budget. Label as 'Over Budget', 'At Risk' (>80%), or 'Healthy'.\n\nTables: employees, departments\n\nCASE WHEN on computed values from JOINs — a real financial reporting pattern.",
        hint: "JOIN + GROUP BY to get total salary per dept, then CASE on salary/budget ratio.",
        solution: "SELECT d.name, d.budget, SUM(e.salary) AS total_salary, CASE WHEN SUM(e.salary) > d.budget THEN 'Over Budget' WHEN SUM(e.salary) > d.budget * 0.8 THEN 'At Risk' ELSE 'Healthy' END AS status FROM departments d JOIN employees e ON d.id = e.department_id GROUP BY d.id;",
    },
    {
        id: 169,
        title: "Bonus Calculation",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[LeetCode 1873 variant · Amazon] Write a query to calculate bonuses: employees with odd-numbered IDs and names NOT starting with 'M' get 10% bonus. Everyone else gets $0.\n\nTable: employees\n\nMultiple conditions in CASE WHEN — tests compound boolean logic within conditional expressions.",
        hint: "CASE WHEN id % 2 = 1 AND name NOT LIKE 'M%' THEN salary * 0.1 ELSE 0 END.",
        solution: "SELECT name, salary, CASE WHEN id % 2 = 1 AND name NOT LIKE 'M%' THEN ROUND(salary * 0.1, 2) ELSE 0 END AS bonus FROM employees;",
    },
    {
        id: 170,
        title: "Dynamic Pricing Tiers",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Amazon · Uber] Write a query to apply dynamic pricing: show original price and a discounted price based on category. 'Electronics' gets 10% off, 'Clothing' gets 20% off, others get 5% off.\n\nTable: products\n\nCASE WHEN for business rule application — mirrors real-world pricing engine logic.",
        hint: "CASE WHEN category = 'Electronics' THEN price * 0.9 WHEN 'Clothing' THEN price * 0.8 ELSE price * 0.95 END.",
        solution: "SELECT name, category, price AS original_price, ROUND(CASE WHEN category = 'Electronics' THEN price * 0.90 WHEN category = 'Clothing' THEN price * 0.80 ELSE price * 0.95 END, 2) AS discounted_price FROM products;",
    },
    {
        id: 171,
        title: "Customer Activity Segmentation",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Meta · Netflix] Write a query to segment customers by their order frequency: 'Power User' (>5 orders), 'Active' (3-5 orders), 'Casual' (1-2 orders), 'Inactive' (0 orders).\n\nTables: customers, orders\n\nCASE WHEN with LEFT JOIN + aggregation for user segmentation — a core product analytics question.",
        hint: "LEFT JOIN customers with orders, COUNT orders, then CASE on the count.",
        solution: "SELECT c.name, COUNT(o.id) AS order_count, CASE WHEN COUNT(o.id) > 5 THEN 'Power User' WHEN COUNT(o.id) >= 3 THEN 'Active' WHEN COUNT(o.id) >= 1 THEN 'Casual' ELSE 'Inactive' END AS segment FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.name;",
    },
    {
        id: 172,
        title: "CASE in ORDER BY",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Google · Microsoft] Write a query to sort employees with a custom priority: 'New York' employees first, then 'Seattle', then everyone else. Within each group, sort by salary descending.\n\nTable: employees\n\nCASE WHEN in ORDER BY — a less obvious but powerful technique tested at FAANG.",
        hint: "ORDER BY CASE WHEN city = 'New York' THEN 1 WHEN city = 'Seattle' THEN 2 ELSE 3 END, salary DESC.",
        solution: "SELECT name, city, salary FROM employees ORDER BY CASE WHEN city = 'New York' THEN 1 WHEN city = 'Seattle' THEN 2 ELSE 3 END, salary DESC;",
    },
    {
        id: 173,
        title: "Null-Safe Comparison",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "[Amazon · Meta] Write a query to show each employee and their manager status: 'Has Manager' or 'No Manager (Top Level)' based on whether manager_id is NULL.\n\nTable: employees\n\nCASE WHEN for NULL handling — simpler than COALESCE but more expressive.",
        hint: "CASE WHEN manager_id IS NULL THEN 'No Manager (Top Level)' ELSE 'Has Manager' END.",
        solution: "SELECT name, CASE WHEN manager_id IS NULL THEN 'No Manager (Top Level)' ELSE 'Has Manager' END AS manager_status FROM employees;",
    },
    {
        id: 174,
        title: "Grade Distribution Report",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Google · Apple] Write a query to show a grade distribution for each course: count of A, B, C, and other grades as separate columns.\n\nTable: enrollments\n\nPivoting with CASE WHEN — the same pattern as question 162, applied to a different domain. Repetition builds mastery.",
        hint: "SUM(CASE WHEN grade = 'A' THEN 1 ELSE 0 END) for each grade, GROUP BY course_id.",
        solution: "SELECT course_id, SUM(CASE WHEN grade = 'A' THEN 1 ELSE 0 END) AS grade_A, SUM(CASE WHEN grade = 'B' THEN 1 ELSE 0 END) AS grade_B, SUM(CASE WHEN grade = 'C' THEN 1 ELSE 0 END) AS grade_C, SUM(CASE WHEN grade NOT IN ('A', 'B', 'C') THEN 1 ELSE 0 END) AS other FROM enrollments GROUP BY course_id;",
    },
    {
        id: 175,
        title: "Revenue Comparison — Weekday vs Weekend",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[Uber · Amazon] Write a query to compare total revenue from weekday orders vs weekend orders (completed only). Sunday=0, Saturday=6.\n\nTable: orders\n\nCASE WHEN + date functions + aggregation — combines multiple skills in one question. A real analytics challenge.",
        hint: "Use strftime('%w') to get day number, CASE to classify as weekday/weekend, then SUM.",
        solution: "SELECT CASE WHEN strftime('%w', order_date) IN ('0', '6') THEN 'Weekend' ELSE 'Weekday' END AS day_type, COUNT(*) AS order_count, SUM(amount) AS total_revenue FROM orders WHERE status = 'completed' GROUP BY day_type;",
    },
    {
        id: 176,
        title: "Triangle Judgement",
        category: "CASE WHEN",
        difficulty: "easy",
        description: "[LeetCode 610] For each set of three sides (x, y, z), determine whether they can form a valid triangle. A triangle is valid if the sum of any two sides is greater than the third.\n\nTable: triangles\n\nLeetCode 610 — pure CASE WHEN logic with arithmetic conditions. Tests if you know the triangle inequality theorem in SQL.",
        hint: "CASE WHEN x+y>z AND x+z>y AND y+z>x THEN 'Yes' ELSE 'No' END.",
        solution: "SELECT x, y, z, CASE WHEN x + y > z AND x + z > y AND y + z > x THEN 'Yes' ELSE 'No' END AS triangle FROM triangles;",
    },
    {
        id: 177,
        title: "Count Salary Categories",
        category: "CASE WHEN",
        difficulty: "medium",
        description: "[LeetCode 1907] Classify accounts into salary categories and count how many employees fall in each: 'Low Salary' (<$70K), 'Average Salary' ($70K-$90K), 'High Salary' (>$90K). Every category must appear even if count is 0.\n\nTable: employees\n\nLeetCode 1907 — CASE WHEN bucketing + UNION ALL to ensure missing categories appear. A real-world reporting pattern.",
        hint: "Use three separate SELECTs with UNION ALL, one per category, each counting with WHERE.",
        solution: "SELECT 'Low Salary' AS category, COUNT(*) AS accounts_count FROM employees WHERE salary < 70000 UNION ALL SELECT 'Average Salary', COUNT(*) FROM employees WHERE salary BETWEEN 70000 AND 90000 UNION ALL SELECT 'High Salary', COUNT(*) FROM employees WHERE salary > 90000;",
    },
];
