// CTEs (Common Table Expressions) — 15 FAANG Interview Questions
export const ctes = [
    {
        id: 131,
        title: "Basic CTE — Above Average Salary",
        category: "CTEs",
        difficulty: "easy",
        description: "[Amazon · Google] Rewrite the 'employees above average salary' query using a CTE instead of a subquery.\n\nTable: employees\n\nCTEs make complex queries readable — interviewers expect you to use WITH clauses for multi-step logic.",
        hint: "WITH avg_sal AS (SELECT AVG(salary) AS avg FROM employees) then SELECT ... WHERE salary > avg.",
        solution: "WITH avg_sal AS (SELECT AVG(salary) AS avg FROM employees) SELECT name, salary FROM employees, avg_sal WHERE salary > avg_sal.avg;",
    },
    {
        id: 132,
        title: "CTE for Department Stats",
        category: "CTEs",
        difficulty: "medium",
        description: "[Amazon · Microsoft] Write a CTE that calculates department statistics (employee count, avg salary, total salary), then filter to departments with average salary above $80,000.\n\nTable: employees\n\nCTE as a 'virtual table' that you query from — the most common CTE pattern.",
        hint: "Build the stats in a WITH clause, then SELECT from it with a WHERE filter.",
        solution: "WITH dept_stats AS (SELECT department_id, COUNT(*) AS emp_count, ROUND(AVG(salary), 2) AS avg_salary, SUM(salary) AS total_salary FROM employees GROUP BY department_id) SELECT * FROM dept_stats WHERE avg_salary > 80000;",
    },
    {
        id: 133,
        title: "Multiple CTEs — Revenue Analysis",
        category: "CTEs",
        difficulty: "medium",
        description: "[Google · Meta] Write a query using TWO CTEs: one for customer total spending, another for the overall average spend. Then find customers spending above the average.\n\nTables: orders, customers\n\nMultiple CTEs (comma-separated) — shows you can build multi-step analytical pipelines.",
        hint: "WITH customer_spend AS (...), avg_spend AS (...) SELECT from both.",
        solution: "WITH customer_spend AS (SELECT customer_id, SUM(amount) AS total FROM orders WHERE status = 'completed' GROUP BY customer_id), avg_spend AS (SELECT AVG(total) AS avg_total FROM customer_spend) SELECT c.name, cs.total FROM customer_spend cs JOIN customers c ON cs.customer_id = c.id, avg_spend WHERE cs.total > avg_spend.avg_total ORDER BY cs.total DESC;",
    },
    {
        id: 134,
        title: "CTE for Deduplication",
        category: "CTEs",
        difficulty: "medium",
        description: "[LeetCode 196 pattern · Meta · Google] Using a CTE with ROW_NUMBER, identify and keep only the first occurrence of each email (smallest id). Show the deduplicated employee list.\n\nTable: employees\n\nROW_NUMBER inside a CTE for deduplication — the production-grade approach to removing duplicates.",
        hint: "ROW_NUMBER() PARTITION BY email ORDER BY id, then filter WHERE rn = 1.",
        solution: "WITH deduped AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) AS rn FROM employees) SELECT id, name, email, salary FROM deduped WHERE rn = 1;",
    },
    {
        id: 135,
        title: "Recursive CTE — Generate Numbers",
        category: "CTEs",
        difficulty: "medium",
        description: "[Amazon · Microsoft] Write a recursive CTE to generate numbers from 1 to 10.\n\nNo table needed.\n\nRecursive CTEs are tested at Amazon and Microsoft for data engineering roles. The base case + recursive step pattern is essential.",
        hint: "Base case: SELECT 1. Recursive step: SELECT n + 1 FROM cte WHERE n < 10.",
        solution: "WITH RECURSIVE numbers(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM numbers WHERE n < 10) SELECT n FROM numbers;",
    },
    {
        id: 136,
        title: "CTE for Top N Per Group",
        category: "CTEs",
        difficulty: "medium",
        description: "[LeetCode 185 · Amazon · Meta] Using a CTE, find the top 2 highest-paid employees per department. Show department_id, name, and salary.\n\nTable: employees\n\nThe CTE approach to top-N per group — cleaner than nested subqueries. Interviewers prefer this.",
        hint: "CTE with DENSE_RANK() PARTITION BY department_id, then filter WHERE rank <= 2.",
        solution: "WITH ranked AS (SELECT name, department_id, salary, DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees) SELECT department_id, name, salary FROM ranked WHERE rn <= 2;",
    },
    {
        id: 137,
        title: "CTE for Percentile Classification",
        category: "CTEs",
        difficulty: "hard",
        description: "[Goldman Sachs · Google] Using a CTE with NTILE, classify employees into salary tiers: 'Top 25%', '25-50%', '50-75%', 'Bottom 25%'.\n\nTable: employees\n\nCTE + NTILE + CASE for percentile bucketing — a real analytics pattern used in compensation analysis.",
        hint: "First CTE: assign NTILE(4). Then CASE WHEN quartile = 4 THEN 'Top 25%' etc.",
        solution: "WITH quartiles AS (SELECT name, salary, NTILE(4) OVER (ORDER BY salary) AS quartile FROM employees) SELECT name, salary, CASE WHEN quartile = 4 THEN 'Top 25%' WHEN quartile = 3 THEN '25-50%' WHEN quartile = 2 THEN '50-75%' ELSE 'Bottom 25%' END AS tier FROM quartiles ORDER BY salary DESC;",
    },
    {
        id: 138,
        title: "CTE — Month-over-Month Revenue",
        category: "CTEs",
        difficulty: "hard",
        description: "[Amazon · Netflix] Write a CTE to compute monthly revenue and show the percentage change from the previous month.\n\nTable: orders\n\nCTE + LAG for period-over-period analysis — one of the most common real-world analytics questions.",
        hint: "CTE 1: monthly revenue. Main query: use LAG to get previous month's revenue, then compute % change.",
        solution: "WITH monthly AS (SELECT strftime('%Y-%m', order_date) AS month, SUM(amount) AS revenue FROM orders WHERE status = 'completed' GROUP BY month) SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev_month, ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0 / LAG(revenue) OVER (ORDER BY month), 2) AS pct_change FROM monthly;",
    },
    {
        id: 139,
        title: "Recursive CTE — Fibonacci",
        category: "CTEs",
        difficulty: "hard",
        description: "[Microsoft · Goldman Sachs] Write a recursive CTE to generate the first 10 Fibonacci numbers.\n\nNo table needed.\n\nAdvanced recursive CTE — tests your understanding of carrying state between iterations.",
        hint: "Track current value AND next value. Each step: new val = next_val, new next = val + next_val.",
        solution: "WITH RECURSIVE fib(n, val, next_val) AS (SELECT 1, 0, 1 UNION ALL SELECT n + 1, next_val, val + next_val FROM fib WHERE n < 10) SELECT n, val AS fibonacci FROM fib;",
    },
    {
        id: 140,
        title: "CTE for Cohort Analysis",
        category: "CTEs",
        difficulty: "hard",
        description: "[Meta · Amazon] Write a CTE to perform a basic cohort analysis: find how many customers signed up each year and their total spending on completed orders.\n\nTables: customers, orders\n\nCohort analysis is a top data science interview question at Meta and Amazon.",
        hint: "CTE 1: extract signup year from join_date. Then JOIN with orders and GROUP BY year.",
        solution: "WITH cohorts AS (SELECT id, name, strftime('%Y', join_date) AS signup_year FROM customers) SELECT c.signup_year, COUNT(DISTINCT c.id) AS customers, COALESCE(SUM(o.amount), 0) AS total_revenue FROM cohorts c LEFT JOIN orders o ON c.id = o.customer_id AND o.status = 'completed' GROUP BY c.signup_year ORDER BY c.signup_year;",
    },
    {
        id: 141,
        title: "Recursive CTE — Employee Hierarchy",
        category: "CTEs",
        difficulty: "hard",
        description: "[Amazon · Microsoft] Write a recursive CTE to display the full management hierarchy. Show each employee, their manager, and their level (CEO = level 1).\n\nTable: employees (manager_id → id)\n\nRecursive CTE for tree traversal — the #1 recursive CTE question at FAANG. Tests org chart / hierarchy navigation.",
        hint: "Base case: WHERE manager_id IS NULL (top of hierarchy). Recursive: JOIN employees ON manager_id = cte.id.",
        solution: "WITH RECURSIVE hierarchy AS (SELECT id, name, manager_id, 1 AS level FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.name, e.manager_id, h.level + 1 FROM employees e JOIN hierarchy h ON e.manager_id = h.id) SELECT name, manager_id, level FROM hierarchy ORDER BY level, name;",
    },
    {
        id: 142,
        title: "CTE for Gap Detection",
        category: "CTEs",
        difficulty: "hard",
        description: "[Goldman Sachs · Amazon] Write a recursive CTE to find missing (gap) employee IDs between 1 and 20.\n\nTable: employees\n\nGap detection — generate a sequence and LEFT JOIN to find missing values. Common in financial data analysis.",
        hint: "Recursive CTE generates 1-20, then LEFT JOIN with employees to find where id IS NULL.",
        solution: "WITH RECURSIVE all_ids(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM all_ids WHERE n < 20) SELECT n AS missing_id FROM all_ids LEFT JOIN employees ON all_ids.n = employees.id WHERE employees.id IS NULL;",
    },
    {
        id: 143,
        title: "CTE for Running Comparison",
        category: "CTEs",
        difficulty: "medium",
        description: "[Google · LinkedIn] Write a CTE to show each employee's salary alongside their department's average and the company average, plus the difference from both.\n\nTables: employees, departments\n\nMulti-level comparison using CTEs — cleaner than multiple subqueries.",
        hint: "CTE for dept averages, cross-join with company average, then compute differences.",
        solution: "WITH dept_avg AS (SELECT department_id, ROUND(AVG(salary), 2) AS avg_sal FROM employees GROUP BY department_id), company_avg AS (SELECT ROUND(AVG(salary), 2) AS avg_sal FROM employees) SELECT e.name, e.salary, da.avg_sal AS dept_avg, ca.avg_sal AS company_avg, ROUND(e.salary - da.avg_sal, 2) AS diff_from_dept, ROUND(e.salary - ca.avg_sal, 2) AS diff_from_company FROM employees e JOIN dept_avg da ON e.department_id = da.department_id, company_avg ca;",
    },
    {
        id: 144,
        title: "CTE for Customer Segmentation",
        category: "CTEs",
        difficulty: "medium",
        description: "[Amazon · Uber] Use a CTE to segment customers into 'High Value' (>$500 total), 'Medium Value' ($200-$500), and 'Low Value' (<$200) based on their total completed order spending.\n\nTables: customers, orders\n\nBusiness segmentation using CTE + CASE — a very practical analytics interview question.",
        hint: "CTE computes total per customer. Main query uses CASE to assign segments.",
        solution: "WITH spend AS (SELECT customer_id, SUM(amount) AS total FROM orders WHERE status = 'completed' GROUP BY customer_id) SELECT c.name, COALESCE(s.total, 0) AS total_spent, CASE WHEN COALESCE(s.total, 0) > 500 THEN 'High Value' WHEN COALESCE(s.total, 0) >= 200 THEN 'Medium Value' ELSE 'Low Value' END AS segment FROM customers c LEFT JOIN spend s ON c.id = s.customer_id ORDER BY total_spent DESC;",
    },
    {
        id: 145,
        title: "CTE for Cumulative Distribution",
        category: "CTEs",
        difficulty: "hard",
        description: "[Google · Goldman Sachs] Write a CTE to show a cumulative salary distribution: for each salary level, what percentage of employees earn that amount or less?\n\nTable: employees\n\nCumulative distribution function (CDF) — a statistics + SQL crossover question tested at quantitative finance firms.",
        hint: "CTE with COUNT and running COUNT OVER (ORDER BY salary), then compute percentage.",
        solution: "WITH salary_dist AS (SELECT salary, COUNT(*) OVER () AS total, ROW_NUMBER() OVER (ORDER BY salary) AS rn FROM employees) SELECT salary, ROUND(rn * 100.0 / total, 2) AS cumulative_pct FROM salary_dist ORDER BY salary;",
    },
    {
        id: 146,
        title: "Report Contiguous Dates",
        category: "CTEs",
        difficulty: "hard",
        description: "[LeetCode 1357] Write a CTE-based solution to find periods of consecutive days where each day has at least one order. Report the start and end date of each consecutive period.\n\nTable: orders\n\nLeetCode 1357 — gaps-and-islands problem using date difference minus ROW_NUMBER to group consecutive dates.",
        hint: "ROW_NUMBER over order_date, subtract from date to get island group key. GROUP BY that key, SELECT MIN/MAX.",
        solution: "WITH daily AS (SELECT DISTINCT strftime('%Y-%m-%d', order_date) AS day FROM orders ORDER BY day), numbered AS (SELECT day, ROW_NUMBER() OVER (ORDER BY day) AS rn FROM daily), islands AS (SELECT day, date(day, '-' || rn || ' days') AS grp FROM numbered) SELECT MIN(day) AS start_date, MAX(day) AS end_date, COUNT(*) AS day_count FROM islands GROUP BY grp ORDER BY start_date;",
    },
    {
        id: 147,
        title: "All People Report to the Given Manager",
        category: "CTEs",
        difficulty: "medium",
        description: "[LeetCode 1405] Find all employees who directly or indirectly report to the manager with id=1. Use a recursive CTE to traverse the full reporting chain.\n\nTable: employees\n\nExact LeetCode 1405 — recursive CTE for multi-level hierarchy traversal. The key recursive SQL pattern for org chart queries.",
        hint: "Base case: WHERE manager_id = 1. Recursive: JOIN employees ON manager_id = cte.id. Exclude id=1 from result.",
        solution: "WITH RECURSIVE reports(id) AS (SELECT id FROM employees WHERE manager_id = 1 UNION ALL SELECT e.id FROM employees e JOIN reports r ON e.manager_id = r.id) SELECT id AS employee_id FROM reports ORDER BY id;",
    },
    {
        id: 148,
        title: "Find the Start and End Number of Continuous Ranges",
        category: "CTEs",
        difficulty: "medium",
        description: "[LeetCode 1420] Find the start and end number of each continuous range in the employees table (treating id as the value).\n\nTable: employees\n\nLeetCode 1420 — classic gaps-and-islands. Subtract ROW_NUMBER from id to get a group key; MIN/MAX per group gives range start/end.",
        hint: "id - ROW_NUMBER() OVER (ORDER BY id) creates a constant for each consecutive group. GROUP BY that constant.",
        solution: "WITH grp AS (SELECT id, id - ROW_NUMBER() OVER (ORDER BY id) AS island FROM employees) SELECT MIN(id) AS start_id, MAX(id) AS end_id FROM grp GROUP BY island ORDER BY start_id;",
    },
    {
        id: 149,
        title: "The Most Recent Three Orders",
        category: "CTEs",
        difficulty: "medium",
        description: "[LeetCode 1671] Find the 3 most recent orders for each customer. Show customer name, customer id, order id, and order date. Order by customer name, then order date descending, then order id.\n\nTables: customers, orders\n\nLeetCode 1671 — ROW_NUMBER OVER (PARTITION BY customer_id ORDER BY order_date DESC), filter <= 3.",
        hint: "CTE with ROW_NUMBER PARTITION BY customer_id ORDER BY order_date DESC, filter WHERE rn <= 3.",
        solution: "WITH ranked AS (SELECT o.id AS order_id, o.order_date, o.customer_id, c.name AS customer_name, ROW_NUMBER() OVER (PARTITION BY o.customer_id ORDER BY o.order_date DESC, o.id) AS rn FROM orders o JOIN customers c ON o.customer_id = c.id) SELECT customer_name, customer_id, order_id, order_date FROM ranked WHERE rn <= 3 ORDER BY customer_name, order_date DESC, order_id;",
    },
    {
        id: 150,
        title: "The Most Recent Orders for Each Product",
        category: "CTEs",
        difficulty: "medium",
        description: "[LeetCode 1688] Find the most recent order(s) for each product. If multiple orders share the same most recent date, report all of them.\n\nTables: products, orders\n\nLeetCode 1688 — RANK() OVER (PARTITION BY product_id ORDER BY order_date DESC), output tied recent orders.",
        hint: "CTE with RANK() PARTITION BY product_id ORDER BY order_date DESC. Filter WHERE rnk = 1.",
        solution: "WITH ranked AS (SELECT p.name AS product_name, p.id AS product_id, o.id AS order_id, o.order_date, RANK() OVER (PARTITION BY o.product_id ORDER BY o.order_date DESC) AS rnk FROM orders o JOIN products p ON o.product_id = p.id) SELECT product_name, product_id, order_id, order_date FROM ranked WHERE rnk = 1 ORDER BY product_name, product_id, order_id;",
    },
    {
        id: 151,
        title: "Most Frequently Ordered Products for Each Customer",
        category: "CTEs",
        difficulty: "medium",
        description: "[LeetCode 1735] Find the most frequently ordered product(s) for each customer. If there's a tie, report all tied products for that customer.\n\nTables: customers, orders, products\n\nLeetCode 1735 — COUNT per customer-product pair, then RANK() to find the top product(s) per customer.",
        hint: "CTE: COUNT per (customer_id, product_id). RANK PARTITION BY customer_id ORDER BY cnt DESC. Filter rnk = 1.",
        solution: "WITH freq AS (SELECT o.customer_id, o.product_id, COUNT(*) AS cnt FROM orders o GROUP BY o.customer_id, o.product_id), ranked AS (SELECT customer_id, product_id, cnt, RANK() OVER (PARTITION BY customer_id ORDER BY cnt DESC) AS rnk FROM freq) SELECT r.customer_id, r.product_id, p.name AS product_name FROM ranked r JOIN products p ON r.product_id = p.id WHERE r.rnk = 1 ORDER BY r.customer_id, r.product_id;",
    },
];

