// CTEs (Common Table Expressions) — 15 problems
export const ctes = [
    {
        id: 131,
        title: "Basic CTE",
        category: "CTEs",
        difficulty: "easy",
        description: "Write a query using a CTE to find employees with salary above the average.\n\nTable: employees",
        hint: "WITH avg_sal AS (SELECT AVG(salary) ...) SELECT ... WHERE salary > avg_sal.",
        solution: "WITH avg_sal AS (SELECT AVG(salary) AS avg FROM employees) SELECT name, salary FROM employees, avg_sal WHERE salary > avg_sal.avg;",
    },
    {
        id: 132,
        title: "CTE for Department Stats",
        category: "CTEs",
        difficulty: "medium",
        description: "Write a query using a CTE to create department statistics (count, avg salary, total salary), then find departments where avg salary > 80000.\n\nTable: employees",
        hint: "Define dept_stats CTE, then filter.",
        solution: "WITH dept_stats AS (SELECT department_id, COUNT(*) AS emp_count, ROUND(AVG(salary), 2) AS avg_salary, SUM(salary) AS total_salary FROM employees GROUP BY department_id) SELECT * FROM dept_stats WHERE avg_salary > 80000;",
    },
    {
        id: 133,
        title: "Multiple CTEs",
        category: "CTEs",
        difficulty: "medium",
        description: "Write a query with two CTEs: one for department averages, one for employee ranks. Then show employees who are above their department average.\n\nTable: employees",
        hint: "WITH dept_avg AS (...), emp_rank AS (...) SELECT ...",
        solution: "WITH dept_avg AS (SELECT department_id, AVG(salary) AS avg_sal FROM employees GROUP BY department_id), above_avg AS (SELECT e.name, e.salary, e.department_id, da.avg_sal FROM employees e JOIN dept_avg da ON e.department_id = da.department_id WHERE e.salary > da.avg_sal) SELECT * FROM above_avg ORDER BY salary DESC;",
    },
    {
        id: 134,
        title: "CTE for Running Total",
        category: "CTEs",
        difficulty: "medium",
        description: "Write a CTE that calculates daily order counts and amounts, then shows a running total.\n\nTable: orders",
        hint: "CTE for daily aggregation, then window function for running total.",
        solution: "WITH daily AS (SELECT order_date, COUNT(*) AS order_count, SUM(amount) AS daily_total FROM orders WHERE status = 'completed' GROUP BY order_date) SELECT order_date, order_count, daily_total, SUM(daily_total) OVER (ORDER BY order_date) AS running_total FROM daily;",
    },
    {
        id: 135,
        title: "Recursive CTE — Numbers 1 to 10",
        category: "CTEs",
        difficulty: "medium",
        description: "Write a recursive CTE to generate numbers from 1 to 10.\n\nNo table needed.",
        hint: "WITH RECURSIVE nums(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM nums WHERE n < 10).",
        solution: "WITH RECURSIVE nums(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM nums WHERE n < 10) SELECT n FROM nums;",
    },
    {
        id: 136,
        title: "Recursive CTE — Employee Hierarchy",
        category: "CTEs",
        difficulty: "hard",
        description: "Write a recursive CTE to show the management chain for all employees (who reports to whom, and at what level).\n\nTable: employees",
        hint: "Start with employees where manager_id IS NULL, recursively join.",
        solution: "WITH RECURSIVE hierarchy AS (SELECT id, name, manager_id, 0 AS level FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.name, e.manager_id, h.level + 1 FROM employees e JOIN hierarchy h ON e.manager_id = h.id) SELECT name, level FROM hierarchy ORDER BY level, name;",
    },
    {
        id: 137,
        title: "CTE for Percentile",
        category: "CTEs",
        difficulty: "hard",
        description: "Using a CTE, classify employees into salary percentiles: Top 25%, 25-50%, 50-75%, Bottom 25%.\n\nTable: employees",
        hint: "Use NTILE(4) in CTE, then CASE WHEN to label.",
        solution: "WITH ranked AS (SELECT name, salary, NTILE(4) OVER (ORDER BY salary DESC) AS quartile FROM employees) SELECT name, salary, CASE quartile WHEN 1 THEN 'Top 25%' WHEN 2 THEN '25-50%' WHEN 3 THEN '50-75%' WHEN 4 THEN 'Bottom 25%' END AS percentile FROM ranked;",
    },
    {
        id: 138,
        title: "CTE with Aggregation Pipeline",
        category: "CTEs",
        difficulty: "medium",
        description: "Write a query with CTEs to: (1) find total spending per customer, (2) rank customers by spending, (3) show only top 5.\n\nTables: orders, customers",
        hint: "Chain CTEs: spending → ranking → filtering.",
        solution: "WITH spending AS (SELECT customer_id, SUM(amount) AS total FROM orders WHERE status = 'completed' GROUP BY customer_id), ranked AS (SELECT s.customer_id, c.name, s.total, RANK() OVER (ORDER BY s.total DESC) AS rnk FROM spending s JOIN customers c ON s.customer_id = c.id) SELECT name, total, rnk FROM ranked WHERE rnk <= 5;",
    },
    {
        id: 139,
        title: "CTE for Year-over-Year",
        category: "CTEs",
        difficulty: "hard",
        description: "Write a CTE to compare monthly revenue between months (showing percentage change).\n\nTable: orders",
        hint: "CTE for monthly totals, then LAG for comparison.",
        solution: "WITH monthly AS (SELECT strftime('%Y-%m', order_date) AS month, SUM(amount) AS revenue FROM orders WHERE status = 'completed' GROUP BY month) SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev_revenue, ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0 / LAG(revenue) OVER (ORDER BY month), 2) AS pct_change FROM monthly;",
    },
    {
        id: 140,
        title: "CTE for Data Deduplication",
        category: "CTEs",
        difficulty: "medium",
        description: "Using a CTE with ROW_NUMBER, find and display unique employees by email (keeping the one with the smallest id).\n\nTable: employees",
        hint: "ROW_NUMBER PARTITION BY email ORDER BY id, then filter rn = 1.",
        solution: "WITH deduped AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) AS rn FROM employees) SELECT id, name, email, salary FROM deduped WHERE rn = 1;",
    },
    {
        id: 141,
        title: "CTE for Cohort Analysis",
        category: "CTEs",
        difficulty: "hard",
        description: "Write a CTE to find how many customers signed up each year and their total spending.\n\nTables: customers, orders",
        hint: "CTE for signup year, join with orders for spending.",
        solution: "WITH cohort AS (SELECT id, name, strftime('%Y', signup_date) AS signup_year FROM customers) SELECT c.signup_year, COUNT(DISTINCT c.id) AS customers, COALESCE(SUM(o.amount), 0) AS total_spent FROM cohort c LEFT JOIN orders o ON c.id = o.customer_id AND o.status = 'completed' GROUP BY c.signup_year ORDER BY c.signup_year;",
    },
    {
        id: 142,
        title: "Recursive CTE — Fibonacci",
        category: "CTEs",
        difficulty: "hard",
        description: "Write a recursive CTE to generate the first 10 Fibonacci numbers.\n\nNo table needed.",
        hint: "WITH RECURSIVE fib(n, a, b) — carry both previous numbers.",
        solution: "WITH RECURSIVE fib(n, val, next_val) AS (SELECT 1, 0, 1 UNION ALL SELECT n + 1, next_val, val + next_val FROM fib WHERE n < 10) SELECT n, val AS fibonacci FROM fib;",
    },
    {
        id: 143,
        title: "CTE for Gap Detection",
        category: "CTEs",
        difficulty: "hard",
        description: "Write a CTE to find gaps in employee IDs (missing IDs between 1 and 20).\n\nTable: employees",
        hint: "Generate numbers 1-20 with recursive CTE, then LEFT JOIN with employees.",
        solution: "WITH RECURSIVE nums(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM nums WHERE n < 20) SELECT n AS missing_id FROM nums WHERE n NOT IN (SELECT id FROM employees);",
    },
    {
        id: 144,
        title: "CTE for Pivot Simulation",
        category: "CTEs",
        difficulty: "hard",
        description: "Write a CTE to show each department as a column with the count of employees (pivot-like in SQLite).\n\nTables: employees, departments",
        hint: "Use SUM(CASE WHEN) for each department.",
        solution: "SELECT SUM(CASE WHEN department_id = 1 THEN 1 ELSE 0 END) AS Engineering, SUM(CASE WHEN department_id = 2 THEN 1 ELSE 0 END) AS Marketing, SUM(CASE WHEN department_id = 3 THEN 1 ELSE 0 END) AS Sales, SUM(CASE WHEN department_id = 4 THEN 1 ELSE 0 END) AS HR, SUM(CASE WHEN department_id = 5 THEN 1 ELSE 0 END) AS Finance FROM employees;",
    },
    {
        id: 145,
        title: "CTE for Cumulative Distribution",
        category: "CTEs",
        difficulty: "hard",
        description: "Write a CTE to show the cumulative distribution of salaries — what percentage of employees earn less than or equal to each salary level.\n\nTable: employees",
        hint: "Count employees at or below each salary / total count.",
        solution: "WITH salary_dist AS (SELECT salary, COUNT(*) OVER (ORDER BY salary) AS cumulative, COUNT(*) OVER () AS total FROM employees) SELECT DISTINCT salary, ROUND(cumulative * 100.0 / total, 2) AS cumulative_pct FROM salary_dist ORDER BY salary;",
    },
];
