// GROUP BY + HAVING — 15 FAANG Interview Questions
export const groupBy = [
    {
        id: 46,
        title: "Departments with Multiple Employees",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[Amazon] Write a query to find departments that have more than 3 employees. Show department_id and employee count.\n\nTable: employees\n\nGROUP BY + HAVING is the most tested aggregate filtering pattern at FAANG.",
        hint: "Use GROUP BY department_id HAVING COUNT(*) > 3.",
        solution: "SELECT department_id, COUNT(*) AS emp_count FROM employees GROUP BY department_id HAVING COUNT(*) > 3;",
    },
    {
        id: 47,
        title: "High-Spending Customers",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Amazon · Flipkart] Write a query to find customers who have spent more than $1,000 in total on completed orders. Show customer_id and total spent, sorted by highest spender first.\n\nTable: orders\n\nCustomer spend thresholds are a core e-commerce analytics question.",
        hint: "Use SUM(amount) with GROUP BY customer_id, filter with HAVING SUM > 1000.",
        solution: "SELECT customer_id, SUM(amount) AS total_spent FROM orders WHERE status = 'completed' GROUP BY customer_id HAVING SUM(amount) > 1000 ORDER BY total_spent DESC;",
    },
    {
        id: 48,
        title: "Classes with 5+ Students",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 596 · Google] Write a query to find all grades that have at least 3 students.\n\nTable: students\n\nA LeetCode classic — straightforward GROUP BY + HAVING COUNT.",
        hint: "GROUP BY grade, HAVING COUNT(*) >= 3.",
        solution: "SELECT grade FROM students GROUP BY grade HAVING COUNT(*) >= 3;",
    },
    {
        id: 49,
        title: "Duplicate Emails (GROUP BY approach)",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 182 · Meta · Google] Write a query to report all duplicate emails. Use the GROUP BY + HAVING approach.\n\nTable: employees\n\nThis is the canonical way to find duplicates — GROUP BY the column, HAVING COUNT > 1.",
        hint: "GROUP BY email HAVING COUNT(*) > 1.",
        solution: "SELECT email FROM employees GROUP BY email HAVING COUNT(*) > 1;",
    },
    {
        id: 50,
        title: "Customers with Repeat Purchases",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Amazon · Netflix] Write a query to find customers who have placed more than 3 orders. Show customer_id and order count.\n\nTable: orders\n\nRepeat customer analysis is a key retention metric asked at subscription and e-commerce companies.",
        hint: "GROUP BY customer_id HAVING COUNT(*) > 3.",
        solution: "SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 3 ORDER BY order_count DESC;",
    },
    {
        id: 51,
        title: "Cities with High Average Salary",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Google · LinkedIn] Write a query to find cities where the average salary exceeds $85,000.\n\nTable: employees\n\nHAVING with AVG — tests if you understand that HAVING filters groups, not individual rows.",
        hint: "GROUP BY city, HAVING AVG(salary) > 85000.",
        solution: "SELECT city, ROUND(AVG(salary), 2) AS avg_salary FROM employees GROUP BY city HAVING AVG(salary) > 85000;",
    },
    {
        id: 52,
        title: "Popular Products (Ordered 3+ Times)",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Uber · Amazon] Write a query to find products that have been ordered more than 2 times. Show product_id and how many times each was ordered.\n\nTable: orders\n\nProduct popularity analysis — a classic e-commerce interview question.",
        hint: "GROUP BY product_id HAVING COUNT(*) > 2.",
        solution: "SELECT product_id, COUNT(*) AS times_ordered FROM orders GROUP BY product_id HAVING COUNT(*) > 2 ORDER BY times_ordered DESC;",
    },
    {
        id: 53,
        title: "Departments Over Budget",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Goldman Sachs · Microsoft] Write a query to find departments where the total employee salary exceeds the department's budget. Show department name, total salary, and budget.\n\nTables: employees, departments\n\nComparing aggregated values against a reference — a real-world financial analysis question.",
        hint: "JOIN employees with departments, GROUP BY department, use HAVING SUM(salary) > budget.",
        solution: "SELECT d.name, SUM(e.salary) AS total_salary, d.budget FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id HAVING SUM(e.salary) > d.budget;",
    },
    {
        id: 54,
        title: "Accounts with High Transaction Volume",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[JPMorgan · Goldman Sachs] Write a query to find accounts with more than 3 transactions. Show account_id and transaction count.\n\nTable: transactions\n\nTransaction volume analysis is a top question at financial institutions.",
        hint: "GROUP BY account_id HAVING COUNT(*) > 3.",
        solution: "SELECT account_id, COUNT(*) AS txn_count FROM transactions GROUP BY account_id HAVING COUNT(*) > 3 ORDER BY txn_count DESC;",
    },
    {
        id: 55,
        title: "Multi-Aggregate Department Report",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Amazon · Microsoft] Write a query to generate a department report showing: employee count, average salary (rounded to 2 decimals), min salary, and max salary. Only include departments with more than 2 employees.\n\nTable: employees\n\nMultiple aggregates in one query — tests your ability to build comprehensive reports.",
        hint: "Use COUNT, AVG, MIN, MAX together in SELECT with GROUP BY and HAVING.",
        solution: "SELECT department_id, COUNT(*) AS emp_count, ROUND(AVG(salary), 2) AS avg_salary, MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM employees GROUP BY department_id HAVING COUNT(*) > 2;",
    },
    {
        id: 56,
        title: "Monthly Order Trends",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Google · Amazon] Write a query to find months in 2023 that had more than 3 orders. Show month number and order count.\n\nTable: orders\n\nTrend analysis with date extraction + HAVING — a common analytics interview scenario.",
        hint: "Extract month with strftime('%m', order_date), GROUP BY month, HAVING COUNT > 3.",
        solution: "SELECT strftime('%m', order_date) AS month, COUNT(*) AS order_count FROM orders WHERE strftime('%Y', order_date) = '2023' GROUP BY month HAVING COUNT(*) > 3;",
    },
    {
        id: 57,
        title: "Instructors Teaching Multiple Courses",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[Apple · Meta] Write a query to find instructors who teach more than 1 course. Show instructor name and course count.\n\nTable: courses\n\nSimple but effective — tests GROUP BY on non-ID columns.",
        hint: "GROUP BY instructor HAVING COUNT(*) > 1.",
        solution: "SELECT instructor, COUNT(*) AS course_count FROM courses GROUP BY instructor HAVING COUNT(*) > 1;",
    },
    {
        id: 58,
        title: "High-Value Product Categories",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Amazon · Walmart] Write a query to find product categories where the total inventory value (price × stock) exceeds $5,000.\n\nTable: products\n\nComputed aggregate with HAVING — tests arithmetic inside aggregate functions.",
        hint: "Use SUM(price * stock) with GROUP BY category, HAVING > 5000.",
        solution: "SELECT category, SUM(price * stock) AS total_value FROM products GROUP BY category HAVING SUM(price * stock) > 5000 ORDER BY total_value DESC;",
    },
    {
        id: 59,
        title: "Avg Order Value Threshold per Customer",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Uber · DoorDash] Write a query to find customers whose average order value exceeds $200 (completed orders only). Show customer_id and average order value.\n\nTable: orders\n\nAVG with HAVING — a key metric for identifying high-value customers in delivery/ride-sharing companies.",
        hint: "AVG(amount) with GROUP BY customer_id, HAVING AVG > 200.",
        solution: "SELECT customer_id, ROUND(AVG(amount), 2) AS avg_order FROM orders WHERE status = 'completed' GROUP BY customer_id HAVING AVG(amount) > 200 ORDER BY avg_order DESC;",
    },
    {
        id: 60,
        title: "Courses with High A-Grade Rate",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[Google · Meta] Write a query to find courses where more than 2 students enrolled. Show course_id, total enrolled, and count of 'A' grades.\n\nTable: enrollments\n\nConditional aggregation (SUM + CASE) inside GROUP BY — a powerful pattern heavily tested at FAANG.",
        hint: "Use SUM(CASE WHEN grade = 'A' THEN 1 ELSE 0 END) with GROUP BY course_id.",
        solution: "SELECT course_id, COUNT(*) AS total_enrolled, SUM(CASE WHEN grade = 'A' THEN 1 ELSE 0 END) AS a_count FROM enrollments GROUP BY course_id HAVING COUNT(*) > 2;",
    },
    {
        id: 61,
        title: "Find Followers Count",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 1729] Write a query to find the number of followers for each user. Return the result ordered by user_id ascending.\n\nTable: followers\n\nLeetCode 1729 — a simple GROUP BY + COUNT, but the table mirrors real social network schemas like Twitter/Instagram.",
        hint: "GROUP BY user_id, COUNT(follower_id).",
        solution: "SELECT user_id, COUNT(follower_id) AS followers_count FROM followers GROUP BY user_id ORDER BY user_id;",
    },
    {
        id: 62,
        title: "Actors and Directors Who Cooperated At Least Three Times",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 1136] Find all the pairs (actor_id, director_id) where the actor has cooperated with the director at least three times.\n\nTable: actors_directors\n\nExact LeetCode 1136 — straightforward GROUP BY two columns + HAVING COUNT >= 3. A warm-up for HAVING mastery.",
        hint: "GROUP BY actor_id, director_id HAVING COUNT(*) >= 3.",
        solution: "SELECT actor_id, director_id FROM actors_directors GROUP BY actor_id, director_id HAVING COUNT(*) >= 3;",
    },
    {
        id: 63,
        title: "Find the Team Size",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 1438] Write a query to find the team size of each employee. Each row in the result should include the employee's id and their team size.\n\nTable: employees (manager_id groups as a team)\n\nLeetCode 1438 — window function COUNT() OVER (PARTITION BY) or a subquery join. Tests knowing when to use GROUP BY vs window functions.",
        hint: "Use COUNT(*) OVER (PARTITION BY manager_id) or join a subquery that counts per manager_id.",
        solution: "SELECT id AS employee_id, COUNT(*) OVER (PARTITION BY manager_id) AS team_size FROM employees;",
    },
    {
        id: 64,
        title: "Customer Order Frequency",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[LeetCode 1654] Find the customer IDs and names of customers who have ordered at least $100 in both January 2023 and February 2023.\n\nTables: customers, orders, products\n\nLeetCode 1654 — conditional aggregation with HAVING on two time-period conditions. A real e-commerce retention pattern.",
        hint: "SUM(CASE WHEN month='2023-01' THEN amount END) >= 100 AND SUM(CASE WHEN month='2023-02' ...) >= 100.",
        solution: "SELECT c.id AS customer_id, c.name AS customer_name FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.name HAVING SUM(CASE WHEN strftime('%Y-%m', o.order_date) = '2023-01' THEN o.amount ELSE 0 END) >= 100 AND SUM(CASE WHEN strftime('%Y-%m', o.order_date) = '2023-02' THEN o.amount ELSE 0 END) >= 100;",
    },
    {
        id: 65,
        title: "Daily Leads and Partners",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 1837] For each date and product, report the number of distinct leads and distinct partners. Order by date then product.\n\nTable: orders (date_id=order_date, product_id=product_id, lead_id=customer_id, partner_id=department_id proxy)\n\nLeetCode 1837 — GROUP BY two columns + COUNT DISTINCT on two other columns.",
        hint: "GROUP BY date_id, make_name. COUNT(DISTINCT lead_id), COUNT(DISTINCT partner_id).",
        solution: "SELECT strftime('%Y-%m-%d', order_date) AS date_id, product_id, COUNT(DISTINCT customer_id) AS unique_leads, COUNT(DISTINCT status) AS unique_partners FROM orders GROUP BY date_id, product_id ORDER BY date_id, product_id;",
    },
    {
        id: 66,
        title: "Number of Calls Between Two Persons",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "[LeetCode 1842] Write a query to report the number of calls and the total call duration between each pair of distinct persons (person1, person2) where person1 < person2.\n\nTable: calls\n\nLeetCode 1842 — UNION to normalize bidirectional calls, then GROUP BY pair + aggregate.",
        hint: "Use UNION to combine (from_id, to_id) and (to_id, from_id), filter WHERE id1 < id2, then GROUP BY pair.",
        solution: "SELECT CASE WHEN from_id < to_id THEN from_id ELSE to_id END AS person1, CASE WHEN from_id < to_id THEN to_id ELSE from_id END AS person2, COUNT(*) AS call_count, SUM(duration) AS total_duration FROM calls GROUP BY person1, person2;",
    },
    {
        id: 67,
        title: "Find Total Time Spent by Each Employee",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 1892] Calculate the total time (in minutes) spent by each employee on each day.\n\nTable: employee_time\n\nLeetCode 1892 — SUM(out_time - in_time) per employee per day. Simple GROUP BY + SUM arithmetic.",
        hint: "SUM(out_time - in_time) GROUP BY emp_id, event_day.",
        solution: "SELECT emp_id, event_day AS day, SUM(out_time - in_time) AS total_time FROM employee_time GROUP BY emp_id, event_day ORDER BY emp_id, day;",
    },
    {
        id: 68,
        title: "Calculate Special Bonus",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 2024] Write a solution to calculate the bonus of each employee. The bonus of an employee is 100% of their salary if the employee's ID is odd and the employee's name does not start with 'M', otherwise 0.\n\nTable: employees\n\nLeetCode 2024 — exact problem. CASE WHEN with id % 2 != 0 AND name NOT LIKE 'M%'. ORDER BY employee_id.",
        hint: "CASE WHEN id % 2 = 1 AND name NOT LIKE 'M%' THEN salary ELSE 0 END AS bonus.",
        solution: "SELECT id AS employee_id, name, CASE WHEN id % 2 = 1 AND name NOT LIKE 'M%' THEN salary ELSE 0 END AS bonus FROM employees ORDER BY employee_id;",
    },
    {
        id: 69,
        title: "The Latest Login in 2020",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 2041] Report the latest login for all users in 2020. Do not include the users who did not login in 2020.\n\nTable: transactions (using transaction_date as login proxy)\n\nLeetCode 2041 — GROUP BY user (account_id), filter year=2020, SELECT MAX(date).",
        hint: "WHERE YEAR = 2020, GROUP BY account_id, SELECT MAX(transaction_date).",
        solution: "SELECT account_id AS user_id, MAX(transaction_date) AS last_stamp FROM transactions WHERE strftime('%Y', transaction_date) = '2024' GROUP BY account_id ORDER BY user_id;",
    },
];
