// GROUP BY + HAVING — 15 problems
export const groupBy = [
    {
        id: 46,
        title: "Departments with Multiple Employees",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "Write a query to find departments that have more than 3 employees. Show department_id and count.\n\nTable: employees",
        hint: "Use GROUP BY with HAVING COUNT(*) > 3.",
        solution: "SELECT department_id, COUNT(*) AS emp_count FROM employees GROUP BY department_id HAVING COUNT(*) > 3;",
    },
    {
        id: 47,
        title: "High-Spending Customers",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find customers who have spent more than $1000 in total on completed orders. Show customer_id and total spent.\n\nTable: orders",
        hint: "Use SUM(amount) with GROUP BY customer_id HAVING SUM > 1000.",
        solution: "SELECT customer_id, SUM(amount) AS total_spent FROM orders WHERE status = 'completed' GROUP BY customer_id HAVING SUM(amount) > 1000 ORDER BY total_spent DESC;",
    },
    {
        id: 48,
        title: "Categories with Low Stock",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find product categories where the average stock is less than 100.\n\nTable: products",
        hint: "Use AVG(stock) with HAVING.",
        solution: "SELECT category, AVG(stock) AS avg_stock FROM products GROUP BY category HAVING AVG(stock) < 100;",
    },
    {
        id: 49,
        title: "Classes More Than 5 Students",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "[LeetCode 596] Write a query to find all grades that have at least 3 students.\n\nTable: students",
        hint: "Use GROUP BY grade HAVING COUNT(*) >= 3.",
        solution: "SELECT grade FROM students GROUP BY grade HAVING COUNT(*) >= 3;",
    },
    {
        id: 50,
        title: "Customers With Repeat Orders",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find customers who have placed more than 3 orders. Show customer_id and order count.\n\nTable: orders",
        hint: "GROUP BY customer_id HAVING COUNT > 3.",
        solution: "SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 3 ORDER BY order_count DESC;",
    },
    {
        id: 51,
        title: "Cities with High Average Salary",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find cities where the average employee salary exceeds 85000.\n\nTable: employees",
        hint: "GROUP BY city HAVING AVG(salary) > 85000.",
        solution: "SELECT city, ROUND(AVG(salary), 2) AS avg_salary FROM employees GROUP BY city HAVING AVG(salary) > 85000;",
    },
    {
        id: 52,
        title: "Popular Products",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find products ordered more than 2 times. Show product_id and order count.\n\nTable: orders",
        hint: "GROUP BY product_id HAVING COUNT > 2.",
        solution: "SELECT product_id, COUNT(*) AS times_ordered FROM orders GROUP BY product_id HAVING COUNT(*) > 2 ORDER BY times_ordered DESC;",
    },
    {
        id: 53,
        title: "Departments Above Budget Average",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find departments where the total employee salary exceeds the department budget.\n\nTables: employees, departments",
        hint: "JOIN employees with departments, then compare SUM(salary) with budget.",
        solution: "SELECT d.name, SUM(e.salary) AS total_salary, d.budget FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id HAVING SUM(e.salary) > d.budget;",
    },
    {
        id: 54,
        title: "Accounts with High Activity",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find account_ids with more than 3 transactions. Show account_id and transaction count.\n\nTable: transactions",
        hint: "GROUP BY account_id HAVING COUNT > 3.",
        solution: "SELECT account_id, COUNT(*) AS txn_count FROM transactions GROUP BY account_id HAVING COUNT(*) > 3 ORDER BY txn_count DESC;",
    },
    {
        id: 55,
        title: "Group By with Multiple Aggregates",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find for each department: the count of employees, average salary, min salary, and max salary. Only show departments with more than 2 employees.\n\nTable: employees",
        hint: "Use multiple aggregate functions in SELECT with HAVING.",
        solution: "SELECT department_id, COUNT(*) AS emp_count, ROUND(AVG(salary), 2) AS avg_salary, MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM employees GROUP BY department_id HAVING COUNT(*) > 2;",
    },
    {
        id: 56,
        title: "Monthly Order Trends",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find months with more than 3 orders in 2023. Show month and order count.\n\nTable: orders",
        hint: "Extract month, GROUP BY, HAVING COUNT > 3.",
        solution: "SELECT strftime('%m', order_date) AS month, COUNT(*) AS order_count FROM orders WHERE strftime('%Y', order_date) = '2023' GROUP BY month HAVING COUNT(*) > 3;",
    },
    {
        id: 57,
        title: "Instructors Teaching Multiple Courses",
        category: "GROUP BY + HAVING",
        difficulty: "easy",
        description: "Write a query to find instructors who teach more than 1 course. Show instructor name and course count.\n\nTable: courses",
        hint: "GROUP BY instructor HAVING COUNT > 1.",
        solution: "SELECT instructor, COUNT(*) AS course_count FROM courses GROUP BY instructor HAVING COUNT(*) > 1;",
    },
    {
        id: 58,
        title: "High-Value Product Categories",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find product categories where the total stock value (price × stock) exceeds $5000.\n\nTable: products",
        hint: "SUM(price * stock) with GROUP BY category.",
        solution: "SELECT category, SUM(price * stock) AS total_value FROM products GROUP BY category HAVING SUM(price * stock) > 5000 ORDER BY total_value DESC;",
    },
    {
        id: 59,
        title: "Average Order Per Customer Threshold",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find customers whose average order value exceeds $200. Show customer_id and avg order value.\n\nTable: orders",
        hint: "AVG(amount) with GROUP BY customer_id HAVING AVG > 200.",
        solution: "SELECT customer_id, ROUND(AVG(amount), 2) AS avg_order FROM orders WHERE status = 'completed' GROUP BY customer_id HAVING AVG(amount) > 200 ORDER BY avg_order DESC;",
    },
    {
        id: 60,
        title: "Grade Distribution Check",
        category: "GROUP BY + HAVING",
        difficulty: "medium",
        description: "Write a query to find course_ids where more than 2 students enrolled. Show course_id, enrollment count, and number of 'A' grades.\n\nTable: enrollments",
        hint: "Use COUNT and conditional SUM for A grades.",
        solution: "SELECT course_id, COUNT(*) AS total_enrolled, SUM(CASE WHEN grade = 'A' THEN 1 ELSE 0 END) AS a_count FROM enrollments GROUP BY course_id HAVING COUNT(*) > 2;",
    },
];
