// JOINs — 25 FAANG Interview Questions
export const joins = [
    {
        id: 61,
        title: "Employee and Department Names",
        category: "JOINs",
        difficulty: "easy",
        description: "[Amazon] Write a query to display each employee's name alongside their department name.\n\nTables: employees, departments\n\nINNER JOIN is the most fundamental join — the starting point of every SQL interview.",
        hint: "JOIN employees with departments ON employees.department_id = departments.id.",
        solution: "SELECT e.name, d.name AS department FROM employees e JOIN departments d ON e.department_id = d.id;",
    },
    {
        id: 62,
        title: "All Departments Including Empty Ones",
        category: "JOINs",
        difficulty: "easy",
        description: "[Google] Write a query to list ALL departments and the count of employees in each. Departments with zero employees must also appear (show 0).\n\nTables: departments, employees\n\nLEFT JOIN preserves all rows from the left table — a key concept tested at every FAANG.",
        hint: "Use LEFT JOIN from departments to employees, then COUNT(e.id) to avoid counting NULLs.",
        solution: "SELECT d.name AS department, COUNT(e.id) AS emp_count FROM departments d LEFT JOIN employees e ON d.id = e.department_id GROUP BY d.id, d.name;",
    },
    {
        id: 63,
        title: "Customer Order Details",
        category: "JOINs",
        difficulty: "easy",
        description: "[Amazon · Flipkart] Write a query to show each order along with the customer name and product name.\n\nTables: orders, customers, products\n\nMulti-table JOIN — a very common pattern in e-commerce interviews.",
        hint: "JOIN orders → customers and orders → products in the same query.",
        solution: "SELECT o.id AS order_id, c.name AS customer, p.name AS product, o.quantity, o.amount FROM orders o JOIN customers c ON o.customer_id = c.id JOIN products p ON o.product_id = p.id;",
    },
    {
        id: 64,
        title: "Employee and Their Manager",
        category: "JOINs",
        difficulty: "easy",
        description: "[Microsoft · Meta] Write a query to show each employee alongside their manager's name. Employees without a manager should still appear (show NULL for manager).\n\nTable: employees (self-referencing via manager_id)\n\nSelf-JOIN is a top pattern — tests your understanding of joining a table with itself.",
        hint: "LEFT JOIN employees e with employees m ON e.manager_id = m.id.",
        solution: "SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;",
    },
    {
        id: 65,
        title: "Employees Earning More Than Their Manager",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 181 · Meta/Facebook · Amazon] Write a query to find employees who earn more than their manager. Show the employee's name.\n\nTable: employees\n\nOne of the most asked FAANG questions — combines self-join with comparison.",
        hint: "Self-join: e.manager_id = m.id, then WHERE e.salary > m.salary.",
        solution: "SELECT e.name AS Employee FROM employees e JOIN employees m ON e.manager_id = m.id WHERE e.salary > m.salary;",
    },
    {
        id: 66,
        title: "Customers Who Never Ordered (JOIN approach)",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 183 · Amazon] Write a query to find customers who have never placed any order using a LEFT JOIN approach.\n\nTables: customers, orders\n\nLEFT JOIN + IS NULL is the performant alternative to NOT IN — interviewers love asking for both approaches.",
        hint: "LEFT JOIN customers with orders, then WHERE o.id IS NULL.",
        solution: "SELECT c.name AS Customers FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL;",
    },
    {
        id: 67,
        title: "Customer Total Spending (Including Zero)",
        category: "JOINs",
        difficulty: "medium",
        description: "[Amazon · Uber] Write a query to show every customer and their total spending on completed orders. Customers who never ordered should show $0. Sort by spending descending.\n\nTables: customers, orders\n\nLEFT JOIN + COALESCE for null handling — a practical real-world analytics pattern.",
        hint: "LEFT JOIN with an ON condition for status. Use COALESCE(SUM(), 0) for customers with no orders.",
        solution: "SELECT c.name, COALESCE(SUM(o.amount), 0) AS total_spent FROM customers c LEFT JOIN orders o ON c.id = o.customer_id AND o.status = 'completed' GROUP BY c.id, c.name ORDER BY total_spent DESC;",
    },
    {
        id: 68,
        title: "Students and Their Courses",
        category: "JOINs",
        difficulty: "easy",
        description: "[Google] Write a query to show each student's name and the courses they are enrolled in.\n\nTables: students, enrollments, courses\n\nThree-table JOIN through a junction table — tests understanding of many-to-many relationships.",
        hint: "JOIN students → enrollments → courses using the foreign keys.",
        solution: "SELECT s.name AS student, c.name AS course, e.grade FROM students s JOIN enrollments e ON s.id = e.student_id JOIN courses c ON e.course_id = c.id ORDER BY s.name;",
    },
    {
        id: 69,
        title: "Cross Join — All Possible Combinations",
        category: "JOINs",
        difficulty: "easy",
        description: "[Apple] Write a query that generates all possible student-course combinations (Cartesian product). Limit to 20 rows.\n\nTables: students, courses\n\nCROSS JOIN interview question — rare but important to know.",
        hint: "Use CROSS JOIN, which produces every row from one table paired with every row from the other.",
        solution: "SELECT s.name AS student, c.name AS course FROM students s CROSS JOIN courses c LIMIT 20;",
    },
    {
        id: 70,
        title: "Department Salary vs Company Average",
        category: "JOINs",
        difficulty: "medium",
        description: "[Google · LinkedIn] Write a query to show each department's name and average salary alongside the company-wide average. Show both rounded to 2 decimals.\n\nTables: employees, departments\n\nComparing group-level aggregates to a global aggregate — a classic analytics interview question.",
        hint: "Use a subquery or cross join with the global AVG to compare alongside per-department AVG.",
        solution: "SELECT d.name AS department, ROUND(AVG(e.salary), 2) AS dept_avg, (SELECT ROUND(AVG(salary), 2) FROM employees) AS company_avg FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id, d.name;",
    },
    {
        id: 71,
        title: "Students Not Enrolled in Any Course",
        category: "JOINs",
        difficulty: "medium",
        description: "[Meta · Microsoft] Write a query to find students who are NOT enrolled in any course.\n\nTables: students, enrollments\n\nLEFT JOIN + NULL check on the many side — the join-based approach to exclusion.",
        hint: "LEFT JOIN students with enrollments, WHERE enrollment IS NULL.",
        solution: "SELECT s.name FROM students s LEFT JOIN enrollments e ON s.id = e.student_id WHERE e.student_id IS NULL;",
    },
    {
        id: 72,
        title: "Orders with Product Category",
        category: "JOINs",
        difficulty: "easy",
        description: "[Amazon] Write a query to show each order with the product name and its category. Only include completed orders.\n\nTables: orders, products\n\nJoin with filter — combining WHERE and JOIN is everyday SQL.",
        hint: "JOIN orders with products and filter WHERE status = 'completed'.",
        solution: "SELECT o.id AS order_id, p.name AS product, p.category, o.amount FROM orders o JOIN products p ON o.product_id = p.id WHERE o.status = 'completed';",
    },
    {
        id: 73,
        title: "Employees in Same City as Department",
        category: "JOINs",
        difficulty: "medium",
        description: "[Microsoft · Goldman Sachs] Write a query to find employees who work in the same city as their department's official location.\n\nTables: employees, departments\n\nJoin with multi-column comparison — tests your ability to add conditions beyond the foreign key.",
        hint: "JOIN on department_id, then add WHERE e.city = d.location.",
        solution: "SELECT e.name, e.city, d.name AS department, d.location FROM employees e JOIN departments d ON e.department_id = d.id WHERE e.city = d.location;",
    },
    {
        id: 74,
        title: "Revenue by Country",
        category: "JOINs",
        difficulty: "medium",
        description: "[Amazon · Stripe] Write a query to find total revenue per country from completed orders. Sort by revenue descending.\n\nTables: orders, customers\n\nJoin + aggregate + group by a dimension from another table — bread and butter of analytics.",
        hint: "JOIN orders with customers, GROUP BY country, SUM(amount).",
        solution: "SELECT c.country, SUM(o.amount) AS total_revenue FROM orders o JOIN customers c ON o.customer_id = c.id WHERE o.status = 'completed' GROUP BY c.country ORDER BY total_revenue DESC;",
    },
    {
        id: 75,
        title: "Combine Two Tables (UNION)",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 175 · Meta] Write a query to create a combined list showing all employee names (labeled 'Employee') and all customer names (labeled 'Customer') in a single result set with a 'source' column.\n\nTables: employees, customers\n\nUNION is a different kind of combining tables — sometimes used alongside JOINs.",
        hint: "Use UNION ALL with a literal 'Employee' or 'Customer' column in each SELECT.",
        solution: "SELECT name, 'Employee' AS source FROM employees UNION ALL SELECT name, 'Customer' AS source FROM customers;",
    },
    {
        id: 76,
        title: "Top Customer Per Country",
        category: "JOINs",
        difficulty: "hard",
        description: "[Google · Uber] Write a query to find the highest-spending customer in each country (completed orders only). Show country, customer name, and total spent.\n\nTables: orders, customers\n\nCorrelated subquery or JOIN + aggregate with per-group max — a hard but common FAANG question.",
        hint: "First compute total spent per customer, then find the max per country using a subquery.",
        solution: "SELECT c.country, c.name, t.total_spent FROM customers c JOIN (SELECT customer_id, SUM(amount) AS total_spent FROM orders WHERE status = 'completed' GROUP BY customer_id) t ON c.id = t.customer_id WHERE t.total_spent = (SELECT MAX(t2.total_spent) FROM customers c2 JOIN (SELECT customer_id, SUM(amount) AS total_spent FROM orders WHERE status = 'completed' GROUP BY customer_id) t2 ON c2.id = t2.customer_id WHERE c2.country = c.country);",
    },
    {
        id: 77,
        title: "Three-Table Join — Employee Salary History",
        category: "JOINs",
        difficulty: "hard",
        description: "[Amazon · Microsoft] Write a query to show each employee's name, department name, and their complete salary history (salary, from_date, to_date). Order by name then start date.\n\nTables: employees, departments, salaries\n\nThree-table join with historical data — tests ability to work with temporal data.",
        hint: "JOIN employees → departments (on department_id) and employees → salaries (on emp_id).",
        solution: "SELECT e.name, d.name AS department, s.salary, s.from_date, s.to_date FROM employees e JOIN departments d ON e.department_id = d.id JOIN salaries s ON e.id = s.emp_id ORDER BY e.name, s.from_date;",
    },
    {
        id: 78,
        title: "Employees with Salary Increase",
        category: "JOINs",
        difficulty: "hard",
        description: "[Google · Goldman Sachs] Write a query to find employees who have received at least one salary increase. Show their name and the number of salary changes.\n\nTables: employees, salaries\n\nCounting records in a related table — tests understanding of one-to-many relationships.",
        hint: "JOIN employees with salaries, GROUP BY employee, HAVING COUNT > 1.",
        solution: "SELECT e.name, COUNT(s.id) AS salary_changes FROM employees e JOIN salaries s ON e.id = s.emp_id GROUP BY e.id, e.name HAVING COUNT(s.id) > 1 ORDER BY salary_changes DESC;",
    },
    {
        id: 79,
        title: "Department Top Earner",
        category: "JOINs",
        difficulty: "hard",
        description: "[LeetCode 184 · Meta · Amazon] Write a query to find the highest-paid employee in each department. Show department name, employee name, and salary.\n\nTables: employees, departments\n\nThe classic 'top per group' pattern — heavily tested at FAANG using JOIN.",
        hint: "Use a correlated subquery: WHERE salary = MAX(salary) for that department, joined with departments.",
        solution: "SELECT d.name AS Department, e.name AS Employee, e.salary AS Salary FROM employees e JOIN departments d ON e.department_id = d.id WHERE e.salary = (SELECT MAX(salary) FROM employees e2 WHERE e2.department_id = e.department_id);",
    },
    {
        id: 80,
        title: "Student Course Count",
        category: "JOINs",
        difficulty: "medium",
        description: "[Apple · Meta] Write a query to show every student and the number of courses they're enrolled in. Students with zero enrollments should display 0. Sort by course count descending.\n\nTables: students, enrollments\n\nLEFT JOIN + COUNT — a classic pattern for counting related records while preserving all parent rows.",
        hint: "LEFT JOIN students with enrollments, COUNT(course_id), GROUP BY student.",
        solution: "SELECT s.name, COUNT(e.course_id) AS course_count FROM students s LEFT JOIN enrollments e ON s.id = e.student_id GROUP BY s.id, s.name ORDER BY course_count DESC;",
    },
    {
        id: 81,
        title: "Cities Where Employees Buy Products",
        category: "JOINs",
        difficulty: "medium",
        description: "[Uber · Amazon] Write a query to find customers who are in the same city as at least one employee. Show distinct customer name and city.\n\nTables: customers, employees\n\nJoin on non-primary-key columns — tests creative use of JOIN conditions.",
        hint: "JOIN customers with employees WHERE c.city = e.city, use DISTINCT.",
        solution: "SELECT DISTINCT c.name AS customer, c.city FROM customers c JOIN employees e ON c.city = e.city;",
    },
    {
        id: 82,
        title: "Consecutive Seat Neighbors",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 603 · Amazon] Write a query to find pairs of employees with consecutive IDs who are in the same department. Show both names and the department_id.\n\nTable: employees\n\nSelf-join on consecutive IDs — a pattern from the classic 'Consecutive Seats' problem.",
        hint: "Self-join where e2.id = e1.id + 1 AND same department.",
        solution: "SELECT e1.name AS employee1, e2.name AS employee2, e1.department_id FROM employees e1 JOIN employees e2 ON e2.id = e1.id + 1 WHERE e1.department_id = e2.department_id;",
    },
    {
        id: 83,
        title: "Products Never Ordered (JOIN approach)",
        category: "JOINs",
        difficulty: "medium",
        description: "[Google · Microsoft] Write a query to find all products that have never been ordered using LEFT JOIN.\n\nTables: products, orders\n\nThe JOIN-based exclusion pattern is more performant than NOT IN on large datasets.",
        hint: "LEFT JOIN products with orders, WHERE o.id IS NULL.",
        solution: "SELECT p.name, p.category FROM products p LEFT JOIN orders o ON p.id = o.product_id WHERE o.id IS NULL;",
    },
    {
        id: 84,
        title: "Employee Department Location",
        category: "JOINs",
        difficulty: "easy",
        description: "[Microsoft] Write a query to display every employee's name, their department name, and the department's location.\n\nTables: employees, departments\n\nA simple two-table JOIN selecting columns from both tables — a fundamental skill check.",
        hint: "JOIN employees with departments on department_id = id.",
        solution: "SELECT e.name, d.name AS dept_name, d.location FROM employees e JOIN departments d ON e.department_id = d.id;",
    },
    {
        id: 85,
        title: "Full Student Report Card",
        category: "JOINs",
        difficulty: "hard",
        description: "[Google · Apple] Write a query to build a complete report card: student name, department, course name, credits, grade, and semester. Order by student name then course name.\n\nTables: students, enrollments, courses\n\nThree-table JOIN producing a detailed report — tests your ability to navigate complex schemas.",
        hint: "JOIN students → enrollments → courses, selecting columns from all three tables.",
        solution: "SELECT s.name AS student, s.department, c.name AS course, c.credits, e.grade, e.semester FROM students s JOIN enrollments e ON s.id = e.student_id JOIN courses c ON e.course_id = c.id ORDER BY s.name, c.name;",
    },
    {
        id: 86,
        title: "Employee Bonus",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 577] Write a query to report the name and bonus amount for each employee. Employees who do NOT have a bonus or whose bonus is less than 1000 should also appear (with NULL bonus).\n\nTables: employees, bonuses\n\nLeetCode 577 — LEFT JOIN to include employees without a bonus. A critical pattern for 'show all from left table' logic.",
        hint: "LEFT JOIN employees with bonuses ON emp_id = id. No HAVING needed — include NULLs.",
        solution: "SELECT e.name, b.bonus FROM employees e LEFT JOIN bonuses b ON e.id = b.emp_id WHERE b.bonus < 1000 OR b.bonus IS NULL;",
    },
    {
        id: 87,
        title: "Product Sales Analysis I",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 1068] Write a query to report the product name, year, and price for each sale.\n\nTables: orders, products\n\nLeetCode 1068 — basic JOIN to enrich sales data with product names from the product catalog.",
        hint: "JOIN orders with products ON product_id = id, select product name, year, amount.",
        solution: "SELECT p.name AS product_name, strftime('%Y', o.order_date) AS year, o.amount AS price FROM orders o JOIN products p ON o.product_id = p.id;",
    },
    {
        id: 88,
        title: "Students and Examinations",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 1280] Write a query to find for each student and each course: the number of times the student attended the exam. Include all student-course pairs even if count = 0.\n\nTables: students, courses, enrollments\n\nLeetCode 1280 — CROSS JOIN to generate all combinations, then LEFT JOIN to count actual attendance.",
        hint: "CROSS JOIN students with courses to get all pairs, then LEFT JOIN enrollments to count.",
        solution: "SELECT s.id AS student_id, s.name AS student_name, c.id AS course_id, c.name AS course_name, COUNT(e.student_id) AS attended_exams FROM students s CROSS JOIN courses c LEFT JOIN enrollments e ON s.id = e.student_id AND c.id = e.course_id GROUP BY s.id, c.id ORDER BY s.id, c.id;",
    },
    {
        id: 89,
        title: "Replace Employee ID With Unique Identifier",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 1378] Show each employee's unique ID (from a second table) and name. If an employee has no unique ID, display NULL.\n\nTables: employees, salaries (using emp_id as the 'unique_id' table)\n\nLeetCode 1378 — LEFT JOIN to preserve all employees even if they don't appear in the ID mapping table.",
        hint: "LEFT JOIN employees (left) with the id-mapping table. NULL will appear for unmatched rows.",
        solution: "SELECT s.emp_id AS unique_id, e.name FROM employees e LEFT JOIN salaries s ON e.id = s.emp_id;",
    },
    {
        id: 90,
        title: "Confirmation Rate",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 1934] Write a query to find the confirmation rate for each user: (# confirmed messages) / (total messages). Round to 2 decimal places. Users with no confirmation messages have a rate of 0.\n\nTables: signups, confirmations\n\nLeetCode 1934 — LEFT JOIN + conditional aggregation for rate calculation. A tricky divide-by-zero edge case must be handled.",
        hint: "LEFT JOIN signups with confirmations. ROUND(AVG(CASE WHEN action='confirmed' THEN 1.0 ELSE 0 END), 2).",
        solution: "SELECT s.user_id, ROUND(AVG(CASE WHEN c.action = 'confirmed' THEN 1.0 ELSE 0 END), 2) AS confirmation_rate FROM signups s LEFT JOIN confirmations c ON s.user_id = c.user_id GROUP BY s.user_id;",
    },
    {
        id: 91,
        title: "Customer Placing the Largest Number of Orders",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 586] Find the customer_number for the customer who has placed the largest number of orders. It is guaranteed that exactly one customer has placed more orders than any other customer.\n\nTable: orders\n\nExact LeetCode 586 — simple GROUP BY with ORDER BY COUNT + LIMIT 1.",
        hint: "GROUP BY customer_number, ORDER BY COUNT(*) DESC, LIMIT 1.",
        solution: "SELECT customer_id AS customer_number FROM orders GROUP BY customer_id ORDER BY COUNT(*) DESC LIMIT 1;",
    },
    {
        id: 92,
        title: "Sales Person",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 607] Report the names of all salespersons who did not have any orders related to the company named 'RED'.\n\nTables: employees, orders, customers\n\nLeetCode 607 — NOT IN with a multi-table subquery. Must join orders→customers to find which orders belong to 'RED'.",
        hint: "Find employee IDs who have orders from customers in 'RED'. Use NOT IN on employees table.",
        solution: "SELECT DISTINCT e.name FROM employees e WHERE e.id NOT IN (SELECT o.customer_id FROM orders o JOIN customers c ON o.customer_id = c.id WHERE c.city = 'Seattle');",
    },
    {
        id: 93,
        title: "Shortest Distance in a Line",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 613] Find the shortest distance between any two points from the employees table (treating salary as points on a number line).\n\nTable: employees\n\nLeetCode 613 — self-join with ABS difference, then pick the MIN. Tests creative use of self-join for geometric problems.",
        hint: "Self-join WHERE e1.id != e2.id, compute ABS(e1.salary - e2.salary), SELECT MIN.",
        solution: "SELECT MIN(ABS(e1.salary - e2.salary)) AS shortest FROM employees e1 JOIN employees e2 ON e1.id != e2.id;",
    },
    {
        id: 94,
        title: "Students With Invalid Departments",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 1481] Find the id and name of all students who are enrolled in a department that no longer exists (not in the departments table).\n\nTables: students, departments\n\nLeetCode 1481 — LEFT JOIN to find students whose department_id has no match in departments.",
        hint: "LEFT JOIN students with departments ON student.department = dept.name, WHERE dept.id IS NULL.",
        solution: "SELECT s.id, s.name FROM students s LEFT JOIN departments d ON s.department = d.name WHERE d.id IS NULL;",
    },
    {
        id: 95,
        title: "Customers Who Bought Products A and B But Not C",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 1536] Find customers who purchased both 'Electronics' AND 'Books' category products, but have NEVER purchased any 'Clothing' product.\n\nTables: customers, orders, products\n\nLeetCode 1536 — multiple EXISTS and NOT EXISTS for set membership. A critical pattern for multi-condition customer segmentation.",
        hint: "WHERE EXISTS (bought Electronics) AND EXISTS (bought Books) AND NOT EXISTS (bought Clothing).",
        solution: "SELECT c.id AS customer_id, c.name AS customer_name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o JOIN products p ON o.product_id = p.id WHERE o.customer_id = c.id AND p.category = 'Electronics') AND EXISTS (SELECT 1 FROM orders o JOIN products p ON o.product_id = p.id WHERE o.customer_id = c.id AND p.category = 'Books') AND NOT EXISTS (SELECT 1 FROM orders o JOIN products p ON o.product_id = p.id WHERE o.customer_id = c.id AND p.category = 'Clothing');",
    },
    {
        id: 96,
        title: "Top Travellers",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 1541] Report the distance travelled by each user, sorted by travelled_distance in descending order. If two or more users have the same distance, order by name ascending. Users with no trips should show 0.\n\nTables: signups (as Users), visits (as Rides with distance proxy)\n\nLeetCode 1541 — LEFT JOIN users with rides, SUM distance, ORDER BY two columns.",
        hint: "LEFT JOIN users with rides table, COALESCE(SUM(distance), 0), ORDER BY distance DESC, name ASC.",
        solution: "SELECT s.user_id, COUNT(v.visit_date) AS visit_count FROM signups s LEFT JOIN visits v ON s.user_id = v.user_id GROUP BY s.user_id ORDER BY visit_count DESC;",
    },
    {
        id: 97,
        title: "Friendly Movies Streamed Last Month",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 1639] Report the distinct titles of kids-friendly movies (rating IN ('G','PG')) streamed in 2024 from the orders table. Show films that were actually watched.\n\nTables: products, orders\n\nLeetCode 1639 — JOIN content with viewing history, filter by rating/date. Tests understanding of JOIN with multi-condition filter.",
        hint: "JOIN products with orders, filter by date range and category = 'Books' (as proxy for family-friendly).",
        solution: "SELECT DISTINCT p.name AS title FROM products p JOIN orders o ON p.id = o.product_id WHERE p.category = 'Books' AND strftime('%Y', o.order_date) = '2023';",
    },
    {
        id: 98,
        title: "Countries You Can Safely Invest In",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 1641] Find cities where the average call duration is strictly greater than the global average call duration.\n\nTable: calls\n\nLeetCode 1641 — GROUP BY city, AVG duration, HAVING avg > (global avg). Uses a scalar subquery for comparison.",
        hint: "GROUP BY from_id/to_id, AVG(duration), HAVING avg > (SELECT AVG(duration) FROM calls).",
        solution: "SELECT from_id AS person1, to_id AS person2, COUNT(*) AS call_count, SUM(duration) AS total_duration FROM (SELECT from_id, to_id FROM calls WHERE from_id < to_id UNION ALL SELECT to_id, from_id FROM calls WHERE from_id > to_id) sub GROUP BY from_id, to_id HAVING AVG(duration) > (SELECT AVG(duration) FROM calls);",
    },
    {
        id: 99,
        title: "Sellers With No Sales",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 1749] Report the names of all sellers who did not make any sales in 2023.\n\nTables: employees, orders\n\nLeetCode 1749 — LEFT JOIN employees to orders filtered by year, WHERE o.id IS NULL (no sales).",
        hint: "LEFT JOIN employees with orders WHERE year='2023', find employees with no matching orders.",
        solution: "SELECT e.name AS seller_name FROM employees e LEFT JOIN orders o ON e.id = o.customer_id AND strftime('%Y', o.order_date) = '2023' WHERE o.id IS NULL ORDER BY e.name;",
    },
    {
        id: 100,
        title: "Find Customers With Positive Revenue This Year",
        category: "JOINs",
        difficulty: "easy",
        description: "[LeetCode 1974] From the transactions table, find customer account IDs that had a positive net balance (total credits - total debits > 0) in 2024.\n\nTable: transactions\n\nLeetCode 1974 — aggregate per customer with conditional SUM, HAVING positive balance. A core financial SQL pattern.",
        hint: "SUM(CASE WHEN type='credit' THEN amount ELSE -amount END) > 0, GROUP BY account_id, year filter.",
        solution: "SELECT account_id FROM transactions WHERE strftime('%Y', transaction_date) = '2024' GROUP BY account_id HAVING SUM(CASE WHEN type = 'credit' THEN amount ELSE -amount END) > 0;",
    },
];
