// JOINs — 25 problems
export const joins = [
    {
        id: 61,
        title: "Employee Department Names",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to display each employee's name along with their department name.\n\nTables: employees, departments",
        hint: "Use INNER JOIN on department_id.",
        solution: "SELECT e.name, d.name AS department FROM employees e JOIN departments d ON e.department_id = d.id;",
    },
    {
        id: 62,
        title: "All Departments (Including Empty)",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to list ALL departments and the count of employees in each. Include departments with no employees.\n\nTables: departments, employees",
        hint: "Use LEFT JOIN from departments to employees.",
        solution: "SELECT d.name AS department, COUNT(e.id) AS emp_count FROM departments d LEFT JOIN employees e ON d.id = e.department_id GROUP BY d.id, d.name;",
    },
    {
        id: 63,
        title: "Customer Order Details",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to show each order with the customer name and product name.\n\nTables: orders, customers, products",
        hint: "Join orders with both customers and products.",
        solution: "SELECT o.id AS order_id, c.name AS customer, p.name AS product, o.quantity, o.amount FROM orders o JOIN customers c ON o.customer_id = c.id JOIN products p ON o.product_id = p.id;",
    },
    {
        id: 64,
        title: "Employees and Their Managers",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 181 variant] Write a query to show each employee and their manager's name. If an employee has no manager, show NULL.\n\nTable: employees",
        hint: "Use a SELF JOIN: employees e LEFT JOIN employees m ON e.manager_id = m.id.",
        solution: "SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;",
    },
    {
        id: 65,
        title: "Employees Earning More Than Manager",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 181] Write a query to find employees who earn more than their managers.\n\nTable: employees",
        hint: "Self join and compare salaries.",
        solution: "SELECT e.name AS Employee FROM employees e JOIN employees m ON e.manager_id = m.id WHERE e.salary > m.salary;",
    },
    {
        id: 66,
        title: "Products Never Ordered",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to find products that have never been ordered.\n\nTables: products, orders",
        hint: "LEFT JOIN products to orders, check where order id IS NULL.",
        solution: "SELECT p.name FROM products p LEFT JOIN orders o ON p.id = o.product_id WHERE o.id IS NULL;",
    },
    {
        id: 67,
        title: "Customer Total Spending",
        category: "JOINs",
        difficulty: "medium",
        description: "Write a query to find each customer's name and their total spending on completed orders. Include customers who haven't ordered.\n\nTables: customers, orders",
        hint: "LEFT JOIN customers to orders, SUM(amount).",
        solution: "SELECT c.name, COALESCE(SUM(o.amount), 0) AS total_spent FROM customers c LEFT JOIN orders o ON c.id = o.customer_id AND o.status = 'completed' GROUP BY c.id, c.name ORDER BY total_spent DESC;",
    },
    {
        id: 68,
        title: "Students and Their Courses",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to show each student's name with the courses they are enrolled in.\n\nTables: students, enrollments, courses",
        hint: "Double JOIN: students → enrollments → courses.",
        solution: "SELECT s.name AS student, c.name AS course, e.grade FROM students s JOIN enrollments e ON s.id = e.student_id JOIN courses c ON e.course_id = c.id ORDER BY s.name;",
    },
    {
        id: 69,
        title: "Cross Join — All Combinations",
        category: "JOINs",
        difficulty: "medium",
        description: "Write a query to generate all possible student-course combinations (even if not enrolled).\n\nTables: students, courses\n\nLimit to first 20 results.",
        hint: "Use CROSS JOIN.",
        solution: "SELECT s.name AS student, c.name AS course FROM students s CROSS JOIN courses c LIMIT 20;",
    },
    {
        id: 70,
        title: "Department-wise Salary Comparison",
        category: "JOINs",
        difficulty: "medium",
        description: "Write a query to show each employee's name, salary, department name, and the department's average salary.\n\nTables: employees, departments",
        hint: "Use a subquery or JOIN with a derived table for department averages.",
        solution: "SELECT e.name, e.salary, d.name AS department, dept_avg.avg_salary FROM employees e JOIN departments d ON e.department_id = d.id JOIN (SELECT department_id, ROUND(AVG(salary), 2) AS avg_salary FROM employees GROUP BY department_id) dept_avg ON e.department_id = dept_avg.department_id;",
    },
    {
        id: 71,
        title: "Students Not Enrolled",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to find students who are not enrolled in any course.\n\nTables: students, enrollments",
        hint: "LEFT JOIN and check WHERE enrollment IS NULL.",
        solution: "SELECT s.name FROM students s LEFT JOIN enrollments e ON s.id = e.student_id WHERE e.student_id IS NULL;",
    },
    {
        id: 72,
        title: "Orders with Product Category",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to show order_id, customer name, product name, and product category for all orders.\n\nTables: orders, customers, products",
        hint: "Triple join.",
        solution: "SELECT o.id, c.name AS customer, p.name AS product, p.category FROM orders o JOIN customers c ON o.customer_id = c.id JOIN products p ON o.product_id = p.id;",
    },
    {
        id: 73,
        title: "Employees in Same City as Department",
        category: "JOINs",
        difficulty: "medium",
        description: "Write a query to find employees who work in the same city as their department's location.\n\nTables: employees, departments",
        hint: "JOIN on department_id AND compare cities.",
        solution: "SELECT e.name, e.city, d.name AS department, d.location FROM employees e JOIN departments d ON e.department_id = d.id WHERE e.city = d.location;",
    },
    {
        id: 74,
        title: "Combine Customer and Employee Tables",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode variant] Write a query to get a combined list of all person names from both employees and customers tables. Remove duplicates.\n\nTables: employees, customers",
        hint: "Use UNION to combine and deduplicate.",
        solution: "SELECT name FROM employees UNION SELECT name FROM customers;",
    },
    {
        id: 75,
        title: "Revenue by Customer Country",
        category: "JOINs",
        difficulty: "medium",
        description: "Write a query to find the total revenue from completed orders grouped by customer country.\n\nTables: orders, customers",
        hint: "JOIN orders with customers, GROUP BY country.",
        solution: "SELECT c.country, SUM(o.amount) AS total_revenue FROM orders o JOIN customers c ON o.customer_id = c.id WHERE o.status = 'completed' GROUP BY c.country ORDER BY total_revenue DESC;",
    },
    {
        id: 76,
        title: "Top Customer Per Country",
        category: "JOINs",
        difficulty: "hard",
        description: "Write a query to find the customer who spent the most in each country (completed orders only). Show country, customer name, and total spent.\n\nTables: orders, customers",
        hint: "First calculate spending per customer, then find max per country.",
        solution: "SELECT c.country, c.name, SUM(o.amount) AS total_spent FROM orders o JOIN customers c ON o.customer_id = c.id WHERE o.status = 'completed' GROUP BY c.id HAVING total_spent = (SELECT MAX(sub.total) FROM (SELECT customer_id, SUM(amount) AS total FROM orders WHERE status = 'completed' GROUP BY customer_id) sub JOIN customers c2 ON sub.customer_id = c2.id WHERE c2.country = c.country);",
    },
    {
        id: 77,
        title: "Multi-Table Join Challenge",
        category: "JOINs",
        difficulty: "hard",
        description: "Write a query to show: employee name, department name, and the total number of orders from customers in the same city as the employee.\n\nTables: employees, departments, customers, orders",
        hint: "Join employees → departments, then find matching city customers and their orders.",
        solution: "SELECT e.name, d.name AS department, COUNT(o.id) AS orders_from_same_city FROM employees e JOIN departments d ON e.department_id = d.id LEFT JOIN customers c ON c.city = e.city LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'completed' GROUP BY e.id ORDER BY orders_from_same_city DESC;",
    },
    {
        id: 78,
        title: "Salary History with Department",
        category: "JOINs",
        difficulty: "medium",
        description: "Write a query to show employee name, department name, and all their historical salaries.\n\nTables: employees, departments, salaries",
        hint: "Triple join: employees → departments and employees → salaries.",
        solution: "SELECT e.name, d.name AS department, s.salary, s.from_date, s.to_date FROM employees e JOIN departments d ON e.department_id = d.id JOIN salaries s ON e.id = s.emp_id ORDER BY e.name, s.from_date;",
    },
    {
        id: 79,
        title: "Department Top Earner",
        category: "JOINs",
        difficulty: "hard",
        description: "[LeetCode 184] For each department, find the employee(s) with the highest salary. Show Department, Employee, Salary.\n\nTables: employees, departments",
        hint: "Use subquery to get max salary per dept, then join.",
        solution: "SELECT d.name AS Department, e.name AS Employee, e.salary AS Salary FROM employees e JOIN departments d ON e.department_id = d.id WHERE (e.department_id, e.salary) IN (SELECT department_id, MAX(salary) FROM employees GROUP BY department_id);",
    },
    {
        id: 80,
        title: "Student Course Count",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query to show each student's name and the number of courses they are enrolled in.\n\nTables: students, enrollments",
        hint: "LEFT JOIN then COUNT.",
        solution: "SELECT s.name, COUNT(e.course_id) AS course_count FROM students s LEFT JOIN enrollments e ON s.id = e.student_id GROUP BY s.id, s.name ORDER BY course_count DESC;",
    },
    {
        id: 81,
        title: "Mutual Customers",
        category: "JOINs",
        difficulty: "medium",
        description: "Write a query to find customers who have ordered products from at least 2 different categories.\n\nTables: orders, products, customers",
        hint: "Join orders→products, GROUP BY customer, HAVING COUNT(DISTINCT category) >= 2.",
        solution: "SELECT c.name, COUNT(DISTINCT p.category) AS categories FROM orders o JOIN customers c ON o.customer_id = c.id JOIN products p ON o.product_id = p.id WHERE o.status = 'completed' GROUP BY c.id HAVING COUNT(DISTINCT p.category) >= 2;",
    },
    {
        id: 82,
        title: "Consecutive Seats",
        category: "JOINs",
        difficulty: "medium",
        description: "[LeetCode 603 variant] Write a query to find pairs of employees who sit next to each other (consecutive IDs) and work in the same department.\n\nTable: employees",
        hint: "Self join where e2.id = e1.id + 1.",
        solution: "SELECT e1.name AS employee1, e2.name AS employee2, e1.department_id FROM employees e1 JOIN employees e2 ON e2.id = e1.id + 1 WHERE e1.department_id = e2.department_id;",
    },
    {
        id: 83,
        title: "Employees Without Orders in Their City",
        category: "JOINs",
        difficulty: "hard",
        description: "Write a query to find employees whose city has NO customers who placed orders.\n\nTables: employees, customers, orders",
        hint: "Use NOT EXISTS or LEFT JOIN.",
        solution: "SELECT DISTINCT e.name, e.city FROM employees e WHERE e.city NOT IN (SELECT DISTINCT c.city FROM customers c JOIN orders o ON c.id = o.customer_id);",
    },
    {
        id: 84,
        title: "Natural Join Example",
        category: "JOINs",
        difficulty: "easy",
        description: "Write a query using a JOIN to find the department name and location for each employee.\n\nTables: employees, departments",
        hint: "Simple JOIN on department_id = id.",
        solution: "SELECT e.name, d.name AS dept_name, d.location FROM employees e JOIN departments d ON e.department_id = d.id;",
    },
    {
        id: 85,
        title: "Full Report Card",
        category: "JOINs",
        difficulty: "hard",
        description: "Write a report showing: student name, department, each course enrolled, course credits, and grade. Order by student name, course name.\n\nTables: students, enrollments, courses",
        hint: "Triple join with proper ordering.",
        solution: "SELECT s.name AS student, s.department, c.name AS course, c.credits, e.grade, e.semester FROM students s JOIN enrollments e ON s.id = e.student_id JOIN courses c ON e.course_id = c.id ORDER BY s.name, c.name;",
    },
];
