// LeetCode SQL Patterns - select-basics.js
export const selectbasics = [
    {
        "id": "584",
        "title": "Find Customer Referee",
        "difficulty": "easy",
        "description": "<p>Table: <code>Customer</code></p>\n\n<pre>\n+-------------+---------+\n| Column Name | Type    |\n+-------------+---------+\n| id          | int     |\n| name        | varchar |\n| referee_id  | int     |\n+-------------+---------+\nIn SQL, id is the primary key column for this table.\nEach row of this table indicates the id of a customer, their name, and the id of the customer who referred them.\n</pre>\n\n<p>&nbsp;</p>\n\n<p>Find the names of the customer that are either:</p>\n\n<ol>\n\t<li><strong>referred by</strong>&nbsp;any&nbsp;customer with&nbsp;<code>id != 2</code>.</li>\n\t<li><strong>not referred by</strong> any customer.</li>\n</ol>\n\n<p>Return the result table in <strong>any order</strong>.</p>\n\n<p>The result format is in the following example.</p>\n\n<p>&nbsp;</p>\n<p><strong class=\"example\">Example 1:</strong></p>\n\n<pre>\n<strong>Input:</strong> \nCustomer table:\n+----+------+------------+\n| id | name | referee_id |\n+----+------+------------+\n| 1  | Will | null       |\n| 2  | Jane | null       |\n| 3  | Alex | 2          |\n| 4  | Bill | null       |\n| 5  | Zack | 1          |\n| 6  | Mark | 2          |\n+----+------+------------+\n<strong>Output:</strong> \n+------+\n| name |\n+------+\n| Will |\n| Jane |\n| Bill |\n| Zack |\n+------+\n</pre>\n",
        "schema": "Create table If Not Exists Customer (id int, name varchar(25), referee_id int)\nTruncate table Customer\ninsert into Customer (id, name, referee_id) values ('1', 'Will', NULL)\ninsert into Customer (id, name, referee_id) values ('2', 'Jane', NULL)\ninsert into Customer (id, name, referee_id) values ('3', 'Alex', '2')\ninsert into Customer (id, name, referee_id) values ('4', 'Bill', NULL)\ninsert into Customer (id, name, referee_id) values ('5', 'Zack', '1')\ninsert into Customer (id, name, referee_id) values ('6', 'Mark', '2')",
        "slug": "find-customer-referee",
        "originalCategory": "select-basics"
    },
    {
        "id": "1148",
        "title": "Article Views I",
        "difficulty": "easy",
        "description": "<p>Table: <code>Views</code></p>\n\n<pre>\n+---------------+---------+\n| Column Name   | Type    |\n+---------------+---------+\n| article_id    | int     |\n| author_id     | int     |\n| viewer_id     | int     |\n| view_date     | date    |\n+---------------+---------+\nThere is no primary key (column with unique values) for this table, the table may have duplicate rows.\nEach row of this table indicates that some viewer viewed an article (written by some author) on some date. \nNote that equal author_id and viewer_id indicate the same person.\n</pre>\n\n<p>&nbsp;</p>\n\n<p>Write a solution to find all the authors that viewed at least one of their own articles.</p>\n\n<p>Return the result table sorted by <code>id</code> in ascending order.</p>\n\n<p>The result format is in the following example.</p>\n\n<p>&nbsp;</p>\n<p><strong class=\"example\">Example 1:</strong></p>\n\n<pre>\n<strong>Input:</strong> \nViews table:\n+------------+-----------+-----------+------------+\n| article_id | author_id | viewer_id | view_date  |\n+------------+-----------+-----------+------------+\n| 1          | 3         | 5         | 2019-08-01 |\n| 1          | 3         | 6         | 2019-08-02 |\n| 2          | 7         | 7         | 2019-08-01 |\n| 2          | 7         | 6         | 2019-08-02 |\n| 4          | 7         | 1         | 2019-07-22 |\n| 3          | 4         | 4         | 2019-07-21 |\n| 3          | 4         | 4         | 2019-07-21 |\n+------------+-----------+-----------+------------+\n<strong>Output:</strong> \n+------+\n| id   |\n+------+\n| 4    |\n| 7    |\n+------+\n</pre>\n",
        "schema": "Create table If Not Exists Views (article_id int, author_id int, viewer_id int, view_date date)\nTruncate table Views\ninsert into Views (article_id, author_id, viewer_id, view_date) values ('1', '3', '5', '2019-08-01')\ninsert into Views (article_id, author_id, viewer_id, view_date) values ('1', '3', '6', '2019-08-02')\ninsert into Views (article_id, author_id, viewer_id, view_date) values ('2', '7', '7', '2019-08-01')\ninsert into Views (article_id, author_id, viewer_id, view_date) values ('2', '7', '6', '2019-08-02')\ninsert into Views (article_id, author_id, viewer_id, view_date) values ('4', '7', '1', '2019-07-22')\ninsert into Views (article_id, author_id, viewer_id, view_date) values ('3', '4', '4', '2019-07-21')\ninsert into Views (article_id, author_id, viewer_id, view_date) values ('3', '4', '4', '2019-07-21')",
        "slug": "article-views-i",
        "originalCategory": "select-basics"
    },
    {
        "id": "1683",
        "title": "Invalid Tweets",
        "difficulty": "easy",
        "description": "<p>Table: <code>Tweets</code></p>\n\n<pre>\n+----------------+---------+\n| Column Name    | Type    |\n+----------------+---------+\n| tweet_id       | int     |\n| content        | varchar |\n+----------------+---------+\ntweet_id is the primary key (column with unique values) for this table.\ncontent consists of alphanumeric characters, &#39;!&#39;, or &#39; &#39; and no other special characters.\nThis table contains all the tweets in a social media app.\n</pre>\n\n<p>&nbsp;</p>\n\n<p>Write a solution to find the IDs of the invalid tweets. The tweet is invalid if the number of characters used in the content of the tweet is <strong>strictly greater</strong> than <code>15</code>.</p>\n\n<p>Return the result table in <strong>any order</strong>.</p>\n\n<p>The result format is in the following example.</p>\n\n<p>&nbsp;</p>\n<p><strong class=\"example\">Example 1:</strong></p>\n\n<pre>\n<strong>Input:</strong> \nTweets table:\n+----------+-----------------------------------+\n| tweet_id | content                           |\n+----------+-----------------------------------+\n| 1        | Let us Code                       |\n| 2        | More than fifteen chars are here! |\n+----------+-----------------------------------+\n<strong>Output:</strong> \n+----------+\n| tweet_id |\n+----------+\n| 2        |\n+----------+\n<strong>Explanation:</strong> \nTweet 1 has length = 11. It is a valid tweet.\nTweet 2 has length = 33. It is an invalid tweet.\n</pre>\n",
        "schema": "Create table If Not Exists Tweets(tweet_id int, content varchar(50))\nTruncate table Tweets\ninsert into Tweets (tweet_id, content) values ('1', 'Let us Code')\ninsert into Tweets (tweet_id, content) values ('2', 'More than fifteen chars are here!')",
        "slug": "invalid-tweets",
        "originalCategory": "select-basics"
    },
    {
        "id": "1757",
        "title": "Recyclable and Low Fat Products",
        "difficulty": "easy",
        "description": "<p>Table: <code>Products</code></p>\n\n<pre>\n+-------------+---------+\n| Column Name | Type    |\n+-------------+---------+\n| product_id  | int     |\n| low_fats    | enum    |\n| recyclable  | enum    |\n+-------------+---------+\nproduct_id is the primary key (column with unique values) for this table.\nlow_fats is an ENUM (category) of type (&#39;Y&#39;, &#39;N&#39;) where &#39;Y&#39; means this product is low fat and &#39;N&#39; means it is not.\nrecyclable is an ENUM (category) of types (&#39;Y&#39;, &#39;N&#39;) where &#39;Y&#39; means this product is recyclable and &#39;N&#39; means it is not.</pre>\n\n<p>&nbsp;</p>\n\n<p>Write a solution to find the ids of products that are both low fat and recyclable.</p>\n\n<p>Return the result table in <strong>any order</strong>.</p>\n\n<p>The result format is in the following example.</p>\n\n<p>&nbsp;</p>\n<p><strong class=\"example\">Example 1:</strong></p>\n\n<pre>\n<strong>Input:</strong> \nProducts table:\n+-------------+----------+------------+\n| product_id  | low_fats | recyclable |\n+-------------+----------+------------+\n| 0           | Y        | N          |\n| 1           | Y        | Y          |\n| 2           | N        | Y          |\n| 3           | Y        | Y          |\n| 4           | N        | N          |\n+-------------+----------+------------+\n<strong>Output:</strong> \n+-------------+\n| product_id  |\n+-------------+\n| 1           |\n| 3           |\n+-------------+\n<strong>Explanation:</strong> Only products 1 and 3 are both low fat and recyclable.\n</pre>\n",
        "schema": "Create table If Not Exists Products (product_id int, low_fats ENUM('Y', 'N'), recyclable ENUM('Y','N'))\nTruncate table Products\ninsert into Products (product_id, low_fats, recyclable) values ('0', 'Y', 'N')\ninsert into Products (product_id, low_fats, recyclable) values ('1', 'Y', 'Y')\ninsert into Products (product_id, low_fats, recyclable) values ('2', 'N', 'Y')\ninsert into Products (product_id, low_fats, recyclable) values ('3', 'Y', 'Y')\ninsert into Products (product_id, low_fats, recyclable) values ('4', 'N', 'N')",
        "slug": "recyclable-and-low-fat-products",
        "originalCategory": "select-basics"
    }
];
