// SELECT Basics — 15 problems
export const selectBasics = [
    {
        id: 1,
        title: "Select All Employees",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display all columns of all employees.\n\nTable: employees",
        hint: "Use SELECT * to get all columns.",
        solution: "SELECT * FROM employees;",
    },
    {
        id: 2,
        title: "Select Specific Columns",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display only the name and salary of all employees.\n\nTable: employees",
        hint: "List the column names you want after SELECT.",
        solution: "SELECT name, salary FROM employees;",
    },
    {
        id: 3,
        title: "Distinct Cities",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to find all unique cities where employees work.\n\nTable: employees",
        hint: "Use SELECT DISTINCT to get unique values.",
        solution: "SELECT DISTINCT city FROM employees;",
    },
    {
        id: 4,
        title: "Aliasing Columns",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display the employee name and salary, renaming them as 'Employee Name' and 'Annual Salary'.\n\nTable: employees",
        hint: "Use AS keyword to rename columns.",
        solution: "SELECT name AS 'Employee Name', salary AS 'Annual Salary' FROM employees;",
    },
    {
        id: 5,
        title: "Calculated Column",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display each employee's name and their monthly salary (annual salary / 12). Name the calculated column 'monthly_salary'.\n\nTable: employees",
        hint: "You can do arithmetic in SELECT: salary / 12.",
        solution: "SELECT name, salary / 12 AS monthly_salary FROM employees;",
    },
    {
        id: 6,
        title: "Limit Results",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display the first 5 employees.\n\nTable: employees",
        hint: "Use LIMIT to restrict the number of rows.",
        solution: "SELECT * FROM employees LIMIT 5;",
    },
    {
        id: 7,
        title: "Order By Salary",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display all employees ordered by salary from highest to lowest.\n\nTable: employees",
        hint: "Use ORDER BY column_name DESC for descending order.",
        solution: "SELECT * FROM employees ORDER BY salary DESC;",
    },
    {
        id: 8,
        title: "Order By Multiple Columns",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display all employees ordered by city (ascending), then by salary (descending) within each city.\n\nTable: employees",
        hint: "Use ORDER BY col1 ASC, col2 DESC.",
        solution: "SELECT * FROM employees ORDER BY city ASC, salary DESC;",
    },
    {
        id: 9,
        title: "Offset and Limit",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display employees 6 through 10 (skip first 5, show next 5).\n\nTable: employees",
        hint: "Use LIMIT with OFFSET: LIMIT 5 OFFSET 5.",
        solution: "SELECT * FROM employees LIMIT 5 OFFSET 5;",
    },
    {
        id: 10,
        title: "String Concatenation",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to display a combined column showing 'name - city' for each employee. Name the column 'employee_location'.\n\nTable: employees",
        hint: "Use || operator to concatenate strings in SQLite.",
        solution: "SELECT name || ' - ' || city AS employee_location FROM employees;",
    },
    {
        id: 11,
        title: "Count All Rows",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to count the total number of employees.\n\nTable: employees",
        hint: "Use COUNT(*) to count rows.",
        solution: "SELECT COUNT(*) AS total_employees FROM employees;",
    },
    {
        id: 12,
        title: "Top N Earners",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to find the top 3 highest-paid employees. Show their name and salary.\n\nTable: employees",
        hint: "Use ORDER BY salary DESC LIMIT 3.",
        solution: "SELECT name, salary FROM employees ORDER BY salary DESC LIMIT 3;",
    },
    {
        id: 13,
        title: "Null Check",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to find all employees who don't have a manager (manager_id is NULL).\n\nTable: employees",
        hint: "Use IS NULL to check for null values.",
        solution: "SELECT * FROM employees WHERE manager_id IS NULL;",
    },
    {
        id: 14,
        title: "Not Null Check",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "Write a query to find all employees who have a manager assigned.\n\nTable: employees",
        hint: "Use IS NOT NULL.",
        solution: "SELECT * FROM employees WHERE manager_id IS NOT NULL;",
    },
    {
        id: 15,
        title: "Duplicate Emails",
        category: "SELECT Basics",
        difficulty: "medium",
        description: "[LeetCode 182] Write a query to find all duplicate emails from the employees table.\n\nTable: employees\n\nNote: Report each duplicate email only once.",
        hint: "Use GROUP BY email HAVING COUNT(*) > 1.",
        solution: "SELECT email FROM employees GROUP BY email HAVING COUNT(*) > 1;",
    },
];
