// SELECT Basics — 15 FAANG Interview Questions
export const selectBasics = [
    {
        id: 1,
        title: "Retrieve All Employee Details",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[Amazon] Write a query to retrieve all details of every employee in the company.\n\nTable: employees\n\nThis is the most fundamental SELECT question — asked as a warm-up in almost every SQL interview.",
        hint: "Use SELECT * to fetch all columns from a table.",
        solution: "SELECT * FROM employees;",
    },
    {
        id: 2,
        title: "Select Specific Columns",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[Google] From the employees table, display only the employee name, their salary, and the city they work in.\n\nTable: employees\n\nInterviewers test if you know how to project specific columns instead of using SELECT *.",
        hint: "List only the columns you need after SELECT.",
        solution: "SELECT name, salary, city FROM employees;",
    },
    {
        id: 3,
        title: "Find Unique Cities",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[Meta/Facebook] Write a query to find all unique cities where the company has employees.\n\nTable: employees\n\nDISTINCT is frequently tested — interviewers want to see if you can eliminate duplicates.",
        hint: "Use SELECT DISTINCT to remove duplicate values.",
        solution: "SELECT DISTINCT city FROM employees;",
    },
    {
        id: 4,
        title: "Column Aliasing",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[Microsoft] Display each employee's name as 'Employee' and their salary as 'Annual_Pay'.\n\nTable: employees\n\nAliasing is critical for readable output — tested in every FAANG data round.",
        hint: "Use the AS keyword to rename columns in the output.",
        solution: "SELECT name AS Employee, salary AS Annual_Pay FROM employees;",
    },
    {
        id: 5,
        title: "Calculate Derived Column",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[Amazon] For each employee, calculate their monthly salary (annual salary divided by 12). Show name and the calculated monthly_salary.\n\nTable: employees\n\nArithmetic expressions in SELECT are a FAANG staple — tests your ability to create derived columns.",
        hint: "You can perform arithmetic directly in SELECT: salary / 12.",
        solution: "SELECT name, ROUND(salary / 12.0, 2) AS monthly_salary FROM employees;",
    },
    {
        id: 6,
        title: "Top N Earners",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[Uber] Write a query to find the top 5 highest-paid employees. Show their name and salary.\n\nTable: employees\n\nTop-N queries using ORDER BY + LIMIT are asked at almost every company.",
        hint: "Use ORDER BY salary DESC with LIMIT 5.",
        solution: "SELECT name, salary FROM employees ORDER BY salary DESC LIMIT 5;",
    },
    {
        id: 7,
        title: "Second Highest Salary",
        category: "SELECT Basics",
        difficulty: "medium",
        description: "[LeetCode 176 · Amazon · Google] Write a query to find the second highest distinct salary from the employees table. If there is no second highest salary, the query should return NULL.\n\nTable: employees\n\nThis is one of the most frequently asked SQL questions across all FAANG companies.",
        hint: "Use a subquery: find the MAX salary that is less than the overall MAX salary. Or use LIMIT 1 OFFSET 1 on distinct salaries.",
        solution: "SELECT MAX(salary) AS SecondHighestSalary FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);",
    },
    {
        id: 8,
        title: "Duplicate Emails",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[LeetCode 182 · Google · Meta] Write a query to find all duplicate emails from the employees table. Report each duplicate email only once.\n\nTable: employees\n\nDuplicate detection using GROUP BY + HAVING is a classic interview pattern.",
        hint: "GROUP BY email and use HAVING COUNT(*) > 1 to find duplicates.",
        solution: "SELECT email FROM employees GROUP BY email HAVING COUNT(*) > 1;",
    },
    {
        id: 9,
        title: "Employees Earning More Than Their Manager",
        category: "SELECT Basics",
        difficulty: "medium",
        description: "[LeetCode 181 · Meta/Facebook · Amazon] Write a query to find employees who earn more than their manager. Show the employee's name as 'Employee'.\n\nTable: employees (manager_id references another employee's id)\n\nSelf-join / self-reference is a classic FAANG pattern. This tests your ability to compare rows within the same table.",
        hint: "Join the employees table with itself: match e.manager_id = m.id, then compare salaries.",
        solution: "SELECT e.name AS Employee FROM employees e JOIN employees m ON e.manager_id = m.id WHERE e.salary > m.salary;",
    },
    {
        id: 10,
        title: "Customers Who Never Ordered",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[LeetCode 183 · Amazon · Uber] Write a query to find all customers who have never placed any order. Show their name as 'Customers'.\n\nTables: customers, orders\n\nNOT IN / NOT EXISTS is one of the most popular FAANG interview patterns.",
        hint: "Use NOT IN with a subquery that selects all customer_ids from orders, or use LEFT JOIN and check for NULL.",
        solution: "SELECT name AS Customers FROM customers WHERE id NOT IN (SELECT DISTINCT customer_id FROM orders);",
    },
    {
        id: 11,
        title: "Rising Temperature",
        category: "SELECT Basics",
        difficulty: "medium",
        description: "[LeetCode 197 · Amazon · Goldman Sachs] Write a query to find all dates' IDs where the temperature was higher than the previous day's temperature in the same city.\n\nTable: weather\n\nComparing consecutive rows is a key FAANG pattern — tests date arithmetic and self-join skills.",
        hint: "Join the weather table with itself where the dates differ by 1 day (use DATE function) and the city matches.",
        solution: "SELECT w1.id FROM weather w1 JOIN weather w2 ON w1.city = w2.city AND DATE(w1.date) = DATE(w2.date, '+1 day') WHERE w1.temperature > w2.temperature;",
    },
    {
        id: 12,
        title: "Nth Highest Salary",
        category: "SELECT Basics",
        difficulty: "medium",
        description: "[LeetCode 177 · Microsoft · Goldman Sachs] Write a query to find the 3rd highest distinct salary from the employees table. If fewer than 3 distinct salaries exist, return NULL.\n\nTable: employees\n\nThis generalizes Q7 — interviewers often follow up with 'Can you find the Nth highest?'",
        hint: "Use SELECT DISTINCT salary, ORDER BY DESC, then LIMIT 1 OFFSET 2 (offset is N-1).",
        solution: "SELECT DISTINCT salary AS ThirdHighestSalary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 2;",
    },
    {
        id: 13,
        title: "Combine Two Columns",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[Meta/Facebook] Write a query to create a full display string for each employee in the format: 'Name - City'. Name the column 'employee_location'.\n\nTable: employees\n\nString concatenation in SELECT is tested at Meta and data-focused roles.",
        hint: "In SQLite, use the || operator to concatenate strings.",
        solution: "SELECT name || ' - ' || city AS employee_location FROM employees;",
    },
    {
        id: 14,
        title: "Swap Values Using CASE",
        category: "SELECT Basics",
        difficulty: "easy",
        description: "[LeetCode 627 · Apple · Amazon] Write a query to display all transactions but swap the type: show 'credit' as 'debit' and 'debit' as 'credit'. Show id, account_id, the swapped type, and amount.\n\nTable: transactions\n\nCASE WHEN inside SELECT is a must-know FAANG pattern for data transformation.",
        hint: "Use CASE WHEN type = 'credit' THEN 'debit' ELSE 'credit' END.",
        solution: "SELECT id, account_id, CASE WHEN type = 'credit' THEN 'debit' WHEN type = 'debit' THEN 'credit' END AS type, amount FROM transactions;",
    },
    {
        id: 15,
        title: "Top Earner in Each City",
        category: "SELECT Basics",
        difficulty: "medium",
        description: "[Google · Uber] Write a query to find the highest-paid employee in each city. Show the city, employee name, and salary.\n\nTable: employees\n\nCorrelated subqueries are heavily tested at Google — this checks your ability to filter rows using per-group max values.",
        hint: "Use a correlated subquery: WHERE salary = (SELECT MAX(salary) FROM employees e2 WHERE e2.city = e.city).",
        solution: "SELECT city, name, salary FROM employees e WHERE salary = (SELECT MAX(salary) FROM employees e2 WHERE e2.city = e.city) ORDER BY salary DESC;",
    },
];
