// String + Date Functions — 15 FAANG Interview Questions
export const stringDate = [
    {
        id: 146,
        title: "Uppercase Employee Names",
        category: "String + Date",
        difficulty: "easy",
        description: "[Amazon · Microsoft] Write a query to display all employee names in uppercase.\n\nTable: employees\n\nUPPER() / LOWER() are the most basic string functions — always tested as warm-up questions.",
        hint: "Use UPPER(name).",
        solution: "SELECT UPPER(name) AS upper_name FROM employees;",
    },
    {
        id: 147,
        title: "Extract First Name",
        category: "String + Date",
        difficulty: "easy",
        description: "[Google · Meta] Write a query to extract only the first name from each employee's full name (the part before the space).\n\nTable: employees\n\nSUBSTR + INSTR for parsing — a fundamental string manipulation pattern.",
        hint: "Use SUBSTR(name, 1, INSTR(name, ' ') - 1) to get everything before the first space.",
        solution: "SELECT SUBSTR(name, 1, INSTR(name, ' ') - 1) AS first_name FROM employees;",
    },
    {
        id: 148,
        title: "Extract Email Domain",
        category: "String + Date",
        difficulty: "medium",
        description: "[Amazon · Google] Write a query to extract the email domain (part after @) for each employee and count how many employees use each domain.\n\nTable: employees\n\nString extraction + GROUP BY — a practical data cleaning question asked in analytics interviews.",
        hint: "SUBSTR(email, INSTR(email, '@') + 1) gets the domain. Then GROUP BY that expression.",
        solution: "SELECT SUBSTR(email, INSTR(email, '@') + 1) AS domain, COUNT(*) AS emp_count FROM employees GROUP BY domain ORDER BY emp_count DESC;",
    },
    {
        id: 149,
        title: "Name Length Analysis",
        category: "String + Date",
        difficulty: "easy",
        description: "[Microsoft] Write a query to show employee names and their character length, ordered by length descending.\n\nTable: employees\n\nLENGTH() — simple but useful, often combined with other functions in follow-ups.",
        hint: "Use LENGTH(name).",
        solution: "SELECT name, LENGTH(name) AS name_length FROM employees ORDER BY name_length DESC;",
    },
    {
        id: 150,
        title: "String Concatenation — Full Info",
        category: "String + Date",
        difficulty: "easy",
        description: "[Amazon] Write a query to create a formatted string for each employee: 'Name works in dept DeptID and earns $Salary'.\n\nTable: employees\n\nString concatenation using || — the SQL way to build formatted output.",
        hint: "Use || operator: name || ' works in dept ' || department_id || ...",
        solution: "SELECT name || ' works in dept ' || department_id || ' and earns $' || salary AS employee_info FROM employees;",
    },
    {
        id: 151,
        title: "Hire Year Extraction",
        category: "String + Date",
        difficulty: "easy",
        description: "[Google · Amazon] Write a query to show each employee's name and the year they were hired.\n\nTable: employees\n\nstrftime('%Y', date) — the most basic date extraction, used constantly in analytics.",
        hint: "Use strftime('%Y', hire_date).",
        solution: "SELECT name, strftime('%Y', hire_date) AS hire_year FROM employees;",
    },
    {
        id: 152,
        title: "Employees Hired in a Specific Month",
        category: "String + Date",
        difficulty: "medium",
        description: "[Meta · Microsoft] Write a query to find employees hired in March of any year.\n\nTable: employees\n\nMonth extraction for filtering — a common pattern for seasonal analysis questions.",
        hint: "Use strftime('%m', hire_date) = '03'.",
        solution: "SELECT name, hire_date FROM employees WHERE strftime('%m', hire_date) = '03';",
    },
    {
        id: 153,
        title: "Days Since Hire (Tenure)",
        category: "String + Date",
        difficulty: "medium",
        description: "[Amazon · Goldman Sachs] Write a query to calculate how many days each employee has been with the company (use '2024-03-01' as the reference date). Sort by longest tenure first.\n\nTable: employees\n\nDate difference using JULIANDAY — the SQLite way to compute intervals. Other DBs use DATEDIFF.",
        hint: "JULIANDAY('2024-03-01') - JULIANDAY(hire_date) gives days as a decimal.",
        solution: "SELECT name, hire_date, CAST(julianday('2024-03-01') - julianday(hire_date) AS INTEGER) AS days_employed FROM employees ORDER BY days_employed DESC;",
    },
    {
        id: 154,
        title: "Orders by Day of Week",
        category: "String + Date",
        difficulty: "medium",
        description: "[Uber · Amazon] Write a query to count orders placed on each day of the week (0=Sunday, 6=Saturday). Which day has the most orders?\n\nTable: orders\n\nDay-of-week analysis — a core analytics question for operations and logistics companies.",
        hint: "Use strftime('%w', order_date) to get day number, then GROUP BY.",
        solution: "SELECT strftime('%w', order_date) AS day_of_week, COUNT(*) AS order_count FROM orders GROUP BY day_of_week ORDER BY order_count DESC;",
    },
    {
        id: 155,
        title: "Quarterly Revenue Report",
        category: "String + Date",
        difficulty: "medium",
        description: "[Amazon · Netflix] Write a query to calculate revenue by quarter for 2023 (completed orders only). Label quarters as Q1, Q2, Q3, Q4.\n\nTable: orders\n\nCASE + date extraction for bucketing — a very common business reporting pattern.",
        hint: "Extract month, then CASE WHEN month IN ('01','02','03') THEN 'Q1' etc.",
        solution: "SELECT CASE WHEN strftime('%m', order_date) IN ('01','02','03') THEN 'Q1' WHEN strftime('%m', order_date) IN ('04','05','06') THEN 'Q2' WHEN strftime('%m', order_date) IN ('07','08','09') THEN 'Q3' ELSE 'Q4' END AS quarter, SUM(amount) AS revenue FROM orders WHERE strftime('%Y', order_date) = '2023' AND status = 'completed' GROUP BY quarter ORDER BY quarter;",
    },
    {
        id: 156,
        title: "Rising Temperature",
        category: "String + Date",
        difficulty: "medium",
        description: "[LeetCode 197 · Amazon · Google] Write a query to find all dates where the temperature was higher than the previous day's temperature in the same city.\n\nTable: weather\n\nThe classic Rising Temperature problem — tests date arithmetic for comparing consecutive days.",
        hint: "Self-join where DATE(w2.date) = DATE(w1.date, '-1 day') and w1.temperature > w2.temperature.",
        solution: "SELECT w1.id FROM weather w1 JOIN weather w2 ON w1.city = w2.city AND DATE(w1.date) = DATE(w2.date, '+1 day') WHERE w1.temperature > w2.temperature;",
    },
    {
        id: 157,
        title: "Customer Lifecycle Span",
        category: "String + Date",
        difficulty: "medium",
        description: "[Amazon · Uber] Write a query to show the number of days between each customer's first and last order.\n\nTable: orders\n\nMIN/MAX of dates per group — a practical customer lifecycle analysis question.",
        hint: "Use MIN and MAX of order_date per customer, then compute the difference.",
        solution: "SELECT customer_id, MIN(order_date) AS first_order, MAX(order_date) AS last_order, CAST(julianday(MAX(order_date)) - julianday(MIN(order_date)) AS INTEGER) AS days_span FROM orders GROUP BY customer_id HAVING COUNT(*) > 1;",
    },
    {
        id: 158,
        title: "Format Date Output",
        category: "String + Date",
        difficulty: "easy",
        description: "[Microsoft] Write a query to display order dates in 'DD/MM/YYYY' format. Limit to 10 results.\n\nTable: orders\n\nDate formatting — different databases have different functions (DATE_FORMAT, TO_CHAR, strftime).",
        hint: "Use strftime('%d/%m/%Y', order_date).",
        solution: "SELECT id, strftime('%d/%m/%Y', order_date) AS formatted_date, amount FROM orders LIMIT 10;",
    },
    {
        id: 159,
        title: "Customer Signups by Year",
        category: "String + Date",
        difficulty: "easy",
        description: "[Meta · Google] Write a query to count customer signups per year. Sort by year.\n\nTable: customers\n\nDate extraction + aggregation — the starting point for cohort analysis.",
        hint: "Extract year from join_date, GROUP BY.",
        solution: "SELECT strftime('%Y', join_date) AS signup_year, COUNT(*) AS signups FROM customers GROUP BY signup_year ORDER BY signup_year;",
    },
    {
        id: 160,
        title: "LIKE Pattern Matching — Email Validation",
        category: "String + Date",
        difficulty: "medium",
        description: "[LeetCode 1683 variant · Meta] Write a query to find employees whose email does NOT follow the pattern 'name@domain.com' (i.e., doesn't contain exactly one '@' followed by a '.'). Show potentially invalid emails.\n\nTable: employees\n\nPattern validation using LIKE and string functions — a real data quality check pattern.",
        hint: "Use LIKE '%@%.%' to match valid patterns. NOT LIKE to find invalid ones.",
        solution: "SELECT name, email FROM employees WHERE email NOT LIKE '%@%.%';",
    },
    {
        id: 161,
        title: "User Activity for Past 30 Days",
        category: "String + Date",
        difficulty: "easy",
        description: "[LeetCode 1141] Find the daily active user count for the 30-day period ending on '2019-07-27'. A user is active on a day if they performed at least one activity.\n\nTable: activities\n\nLeetCode 1141 — date range filter + COUNT DISTINCT. A core product analytics question measuring Daily Active Users (DAU).",
        hint: "WHERE activity_date BETWEEN '2019-06-28' AND '2019-07-27', GROUP BY date, COUNT DISTINCT user_id.",
        solution: "SELECT activity_date AS day, COUNT(DISTINCT user_id) AS active_users FROM activities WHERE activity_date BETWEEN '2019-06-28' AND '2019-07-27' GROUP BY activity_date;",
    },
    {
        id: 162,
        title: "Monthly Transactions I",
        category: "String + Date",
        difficulty: "medium",
        description: "[LeetCode 1193] Write a query to find for each month and country: the number of transactions and their total amount, and the number of approved transactions and their total approved amount.\n\nTable: transactions (use orders as proxy: 'completed' = approved)\n\nLeetCode 1193 — monthly grouping with conditional aggregation. A real reporting pattern for financial dashboards.",
        hint: "GROUP BY month (strftime), count all vs count completed, SUM all vs SUM completed.",
        solution: "SELECT strftime('%Y-%m', order_date) AS month, COUNT(*) AS trans_count, SUM(amount) AS trans_total_amount, SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS approved_count, SUM(CASE WHEN status = 'completed' THEN amount ELSE 0 END) AS approved_total_amount FROM orders GROUP BY month ORDER BY month;",
    },
    {
        id: 163,
        title: "Patients With a Condition",
        category: "String + Date",
        difficulty: "easy",
        description: "[LeetCode 1527] Find patients who have Type I Diabetes. The condition code always starts with 'DIAB1' and may appear anywhere in the conditions string.\n\nTable: patients\n\nLeetCode 1527 — LIKE with leading space pattern is the classic trap. 'DIAB1%' misses 'COUGH DIAB1X' while ' DIAB1%' misses leading occurrences. Use OR with both patterns.",
        hint: "Use: conditions LIKE 'DIAB1%' OR conditions LIKE '% DIAB1%' to match both first and later word positions.",
        solution: "SELECT patient_id, patient_name, conditions FROM patients WHERE conditions LIKE 'DIAB1%' OR conditions LIKE '% DIAB1%';",
    },
    {
        id: 164,
        title: "Fix Names in a Table",
        category: "String + Date",
        difficulty: "easy",
        description: "[LeetCode 1667] Fix employee names to have the first letter uppercase and the rest lowercase. Sort by employee id.\n\nTable: employees\n\nLeetCode 1667 — UPPER(SUBSTR) + LOWER(SUBSTR) = proper case. Tests your ability to combine multiple string functions.",
        hint: "UPPER(SUBSTR(name,1,1)) || LOWER(SUBSTR(name,2)) gives Title Case.",
        solution: "SELECT id, UPPER(SUBSTR(name, 1, 1)) || LOWER(SUBSTR(name, 2)) AS name FROM employees ORDER BY id;",
    },
];
