// String + Date Functions — 15 problems
export const stringDate = [
    {
        id: 146,
        title: "Uppercase Names",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to display all employee names in uppercase.\n\nTable: employees",
        hint: "Use UPPER() function.",
        solution: "SELECT UPPER(name) AS upper_name FROM employees;",
    },
    {
        id: 147,
        title: "Extract First Name",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to extract only the first name from each employee's name.\n\nTable: employees",
        hint: "Use SUBSTR with INSTR to find the space position.",
        solution: "SELECT SUBSTR(name, 1, INSTR(name, ' ') - 1) AS first_name FROM employees;",
    },
    {
        id: 148,
        title: "Email Domain",
        category: "String + Date",
        difficulty: "medium",
        description: "Write a query to extract the domain from each employee's email (part after @).\n\nTable: employees",
        hint: "Use SUBSTR and INSTR to find @ position.",
        solution: "SELECT name, SUBSTR(email, INSTR(email, '@') + 1) AS email_domain FROM employees;",
    },
    {
        id: 149,
        title: "Name Length",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to show employee names and their character length, ordered by length descending.\n\nTable: employees",
        hint: "Use LENGTH() function.",
        solution: "SELECT name, LENGTH(name) AS name_length FROM employees ORDER BY name_length DESC;",
    },
    {
        id: 150,
        title: "Replace in String",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to replace all occurrences of 'company.com' with 'newcompany.com' in employee emails.\n\nTable: employees",
        hint: "Use REPLACE() function.",
        solution: "SELECT name, REPLACE(email, 'company.com', 'newcompany.com') AS new_email FROM employees;",
    },
    {
        id: 151,
        title: "Hire Year Extraction",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to show each employee and the year they were hired.\n\nTable: employees",
        hint: "Use strftime('%Y', hire_date).",
        solution: "SELECT name, strftime('%Y', hire_date) AS hire_year FROM employees;",
    },
    {
        id: 152,
        title: "Employees Hired This Month",
        category: "String + Date",
        difficulty: "medium",
        description: "Write a query to find employees hired in March (any year).\n\nTable: employees",
        hint: "Use strftime('%m', hire_date) = '03'.",
        solution: "SELECT name, hire_date FROM employees WHERE strftime('%m', hire_date) = '03';",
    },
    {
        id: 153,
        title: "Days Since Hire",
        category: "String + Date",
        difficulty: "medium",
        description: "Write a query to show each employee and the number of days since they were hired (use '2024-03-01' as today).\n\nTable: employees",
        hint: "Use julianday to calculate date difference.",
        solution: "SELECT name, hire_date, CAST(julianday('2024-03-01') - julianday(hire_date) AS INTEGER) AS days_employed FROM employees ORDER BY days_employed DESC;",
    },
    {
        id: 154,
        title: "Orders by Day of Week",
        category: "String + Date",
        difficulty: "medium",
        description: "Write a query to count orders placed on each day of the week (0=Sunday, 6=Saturday).\n\nTable: orders",
        hint: "Use strftime('%w', order_date) for day of week.",
        solution: "SELECT strftime('%w', order_date) AS day_of_week, COUNT(*) AS order_count FROM orders GROUP BY day_of_week ORDER BY day_of_week;",
    },
    {
        id: 155,
        title: "Quarterly Revenue",
        category: "String + Date",
        difficulty: "medium",
        description: "Write a query to find revenue by quarter in 2023.\n\nTable: orders",
        hint: "Use CASE WHEN on month to determine quarter.",
        solution: "SELECT CASE WHEN strftime('%m', order_date) IN ('01','02','03') THEN 'Q1' WHEN strftime('%m', order_date) IN ('04','05','06') THEN 'Q2' WHEN strftime('%m', order_date) IN ('07','08','09') THEN 'Q3' ELSE 'Q4' END AS quarter, SUM(amount) AS revenue FROM orders WHERE strftime('%Y', order_date) = '2023' AND status = 'completed' GROUP BY quarter ORDER BY quarter;",
    },
    {
        id: 156,
        title: "Trim Whitespace",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to show how TRIM, LTRIM, and RTRIM work. Select '  hello  ' and show all three trimmed versions.\n\nNo table needed.",
        hint: "SELECT TRIM('  hello  '), LTRIM('  hello  '), RTRIM('  hello  ').",
        solution: "SELECT TRIM('  hello  ') AS trimmed, LTRIM('  hello  ') AS left_trimmed, RTRIM('  hello  ') AS right_trimmed;",
    },
    {
        id: 157,
        title: "Date Difference Between Orders",
        category: "String + Date",
        difficulty: "medium",
        description: "Write a query to show the number of days between each customer's first and last order.\n\nTable: orders",
        hint: "Use MIN and MAX of order_date per customer.",
        solution: "SELECT customer_id, MIN(order_date) AS first_order, MAX(order_date) AS last_order, CAST(julianday(MAX(order_date)) - julianday(MIN(order_date)) AS INTEGER) AS days_span FROM orders GROUP BY customer_id HAVING COUNT(*) > 1;",
    },
    {
        id: 158,
        title: "Format Date Output",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to display order dates in 'DD/MM/YYYY' format.\n\nTable: orders\n\nLimit to 10 results.",
        hint: "Use strftime('%d/%m/%Y', order_date).",
        solution: "SELECT id, strftime('%d/%m/%Y', order_date) AS formatted_date, amount FROM orders LIMIT 10;",
    },
    {
        id: 159,
        title: "Customers by Signup Year",
        category: "String + Date",
        difficulty: "easy",
        description: "Write a query to count the number of customer signups per year.\n\nTable: customers",
        hint: "Extract year from signup_date, GROUP BY.",
        solution: "SELECT strftime('%Y', signup_date) AS signup_year, COUNT(*) AS signups FROM customers GROUP BY signup_year ORDER BY signup_year;",
    },
    {
        id: 160,
        title: "Reverse a String",
        category: "String + Date",
        difficulty: "medium",
        description: "[LeetCode variant] SQLite doesn't have a REVERSE function. Write a creative query to check if any employee name is a palindrome.\n\nTable: employees\n\nHint: This is tricky in SQLite! Just show all names and their reversed first character + last character.",
        hint: "Use SUBSTR to compare first and last characters.",
        solution: "SELECT name, SUBSTR(name, 1, 1) AS first_char, SUBSTR(name, LENGTH(name), 1) AS last_char, CASE WHEN LOWER(SUBSTR(name, 1, 1)) = LOWER(SUBSTR(name, LENGTH(name), 1)) THEN 'Maybe' ELSE 'No' END AS could_be_palindrome FROM employees;",
    },
];
