// Subqueries — 20 FAANG Interview Questions
export const subqueries = [
    {
        id: 86,
        title: "Employees Above Average Salary",
        category: "Subqueries",
        difficulty: "easy",
        description: "[Amazon · Google] Write a query to find all employees who earn more than the company-wide average salary. Show name and salary.\n\nTable: employees\n\nScalar subquery in WHERE — the most fundamental subquery pattern tested at FAANG.",
        hint: "Use WHERE salary > (SELECT AVG(salary) FROM employees).",
        solution: "SELECT name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);",
    },
    {
        id: 87,
        title: "Employees in the Largest Department",
        category: "Subqueries",
        difficulty: "medium",
        description: "[Amazon · Meta] Write a query to find all employees who work in the department with the most employees.\n\nTable: employees\n\nNested subquery with GROUP BY — tests your ability to chain subqueries.",
        hint: "First find the department_id with the highest COUNT, then filter employees by that department.",
        solution: "SELECT * FROM employees WHERE department_id = (SELECT department_id FROM employees GROUP BY department_id ORDER BY COUNT(*) DESC LIMIT 1);",
    },
    {
        id: 88,
        title: "Second Highest Salary (Subquery)",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 176 · Amazon · Google] Write a query to find the second highest distinct salary. Return NULL if it doesn't exist.\n\nTable: employees\n\nThe #1 most asked SQL subquery question. The outer SELECT wrapper ensures NULL is returned if no result exists.",
        hint: "Wrap the LIMIT/OFFSET query in an outer SELECT to handle the NULL case.",
        solution: "SELECT (SELECT DISTINCT salary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 1) AS SecondHighestSalary;",
    },
    {
        id: 89,
        title: "Products Above Average Price",
        category: "Subqueries",
        difficulty: "easy",
        description: "[Microsoft] Write a query to find all products priced above the average product price. Show name, category, and price.\n\nTable: products\n\nAnother scalar subquery comparison — simple but frequently tested.",
        hint: "WHERE price > (SELECT AVG(price) FROM products).",
        solution: "SELECT name, category, price FROM products WHERE price > (SELECT AVG(price) FROM products);",
    },
    {
        id: 90,
        title: "Department with Highest Avg Salary",
        category: "Subqueries",
        difficulty: "medium",
        description: "[Google · Goldman Sachs] Write a query to find the department with the highest average salary. Show department name and average salary.\n\nTables: employees, departments\n\nSubquery in FROM (derived table) — a key pattern for comparing group-level aggregates.",
        hint: "Compute AVG per department in a subquery, then ORDER BY and LIMIT 1.",
        solution: "SELECT d.name AS department, ROUND(AVG(e.salary), 2) AS avg_salary FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id ORDER BY avg_salary DESC LIMIT 1;",
    },
    {
        id: 91,
        title: "Department Highest Salary (Correlated)",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 184 · Meta · Amazon] Write a query to find the employee(s) with the highest salary in each department. Show name, salary, and department_id.\n\nTable: employees\n\nCorrelated subquery — the subquery references the outer query. This is a MUST-KNOW FAANG pattern.",
        hint: "WHERE salary = (SELECT MAX(salary) FROM employees e2 WHERE e2.department_id = e.department_id).",
        solution: "SELECT name, salary, department_id FROM employees e WHERE salary = (SELECT MAX(salary) FROM employees e2 WHERE e2.department_id = e.department_id);",
    },
    {
        id: 92,
        title: "EXISTS — Customers with Orders",
        category: "Subqueries",
        difficulty: "medium",
        description: "[Amazon · Meta] Write a query to find customers who have placed at least one order using the EXISTS keyword.\n\nTables: customers, orders\n\nEXISTS vs IN — interviewers often ask you to explain the difference and when to use each.",
        hint: "Use WHERE EXISTS (SELECT 1 FROM orders WHERE customer_id = c.id).",
        solution: "SELECT c.name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);",
    },
    {
        id: 93,
        title: "NOT EXISTS — Customers Without Orders",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 183 · Amazon] Write a query to find customers who have NEVER placed an order, using NOT EXISTS.\n\nTables: customers, orders\n\nNOT EXISTS is often the most efficient exclusion pattern — critical for large-scale data interviews.",
        hint: "Use WHERE NOT EXISTS (SELECT 1 FROM orders WHERE customer_id = c.id).",
        solution: "SELECT c.name AS Customers FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);",
    },
    {
        id: 94,
        title: "Scalar Subquery in SELECT",
        category: "Subqueries",
        difficulty: "medium",
        description: "[Google · Microsoft] Write a query to show each employee's name, salary, and the overall company average salary in the same row.\n\nTable: employees\n\nSubquery in the SELECT clause — produces a computed column for every row.",
        hint: "Use (SELECT ROUND(AVG(salary), 2) FROM employees) AS company_avg in your SELECT list.",
        solution: "SELECT name, salary, (SELECT ROUND(AVG(salary), 2) FROM employees) AS company_avg FROM employees;",
    },
    {
        id: 95,
        title: "IN with Subquery — Department Filter",
        category: "Subqueries",
        difficulty: "easy",
        description: "[Uber · Amazon] Write a query to find all employees who work in departments located in 'New York' or 'Seattle'.\n\nTables: employees, departments\n\nIN with a subquery that returns a list — the classic multi-value subquery pattern.",
        hint: "WHERE department_id IN (SELECT id FROM departments WHERE location IN ('New York', 'Seattle')).",
        solution: "SELECT name, salary FROM employees WHERE department_id IN (SELECT id FROM departments WHERE location IN ('New York', 'Seattle'));",
    },
    {
        id: 96,
        title: "Rank by Salary Using Subquery",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 178 · Amazon · Google] Write a query to display each employee's name, salary, and how many employees earn MORE than them (as 'higher_earners'). Sort by salary descending.\n\nTable: employees\n\nCorrelated subquery for ranking — the pre-window-function approach to RANK. Still heavily asked.",
        hint: "Use (SELECT COUNT(*) FROM employees e2 WHERE e2.salary > e.salary) AS higher_earners.",
        solution: "SELECT name, salary, (SELECT COUNT(*) FROM employees e2 WHERE e2.salary > e.salary) AS higher_earners FROM employees ORDER BY salary DESC;",
    },
    {
        id: 97,
        title: "Employees with Same Salary",
        category: "Subqueries",
        difficulty: "medium",
        description: "[Meta · Microsoft] Write a query to find pairs of employees who earn exactly the same salary. Show both names and the salary. Avoid duplicate pairs.\n\nTable: employees\n\nSelf-join with inequality — tests your ability to avoid duplicate and self-matching pairs.",
        hint: "Self-join WHERE e1.salary = e2.salary AND e1.id < e2.id to avoid duplicates.",
        solution: "SELECT e1.name AS emp1, e2.name AS emp2, e1.salary FROM employees e1 JOIN employees e2 ON e1.salary = e2.salary AND e1.id < e2.id;",
    },
    {
        id: 98,
        title: "Most Frequently Ordered Product",
        category: "Subqueries",
        difficulty: "hard",
        description: "[LeetCode 1596 · Amazon] Write a query to find the most frequently ordered product(s). Show product name and order count.\n\nTables: products, orders\n\nSubquery to find MAX of an aggregate — a pattern for 'find the top' questions.",
        hint: "First find order counts per product, then filter for the one(s) matching the MAX count.",
        solution: "SELECT p.name, COUNT(*) AS order_count FROM products p JOIN orders o ON p.id = o.product_id GROUP BY p.id HAVING COUNT(*) = (SELECT MAX(cnt) FROM (SELECT COUNT(*) AS cnt FROM orders GROUP BY product_id));",
    },
    {
        id: 99,
        title: "Second Most Recent Order per Customer",
        category: "Subqueries",
        difficulty: "hard",
        description: "[Amazon · Google] Write a query to find each customer's second most recent order. Show customer_id, order_id, and order_date.\n\nTable: orders\n\nCorrelated subquery for 'Nth per group' — tests ranking within groups without window functions.",
        hint: "Use a correlated subquery to count how many orders for the same customer have a later date.",
        solution: "SELECT customer_id, id AS order_id, order_date FROM orders o1 WHERE (SELECT COUNT(*) FROM orders o2 WHERE o2.customer_id = o1.customer_id AND o2.order_date > o1.order_date) = 1;",
    },
    {
        id: 100,
        title: "Departments Above Company Average Salary",
        category: "Subqueries",
        difficulty: "medium",
        description: "[Google · LinkedIn] Write a query to find departments whose average salary is above the company-wide average. Show department name and its average salary.\n\nTables: employees, departments\n\nComparing group average to global average — a layered subquery pattern.",
        hint: "GROUP BY department, HAVING AVG(salary) > (SELECT AVG(salary) FROM employees).",
        solution: "SELECT d.name AS department, ROUND(AVG(e.salary), 2) AS dept_avg FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id HAVING AVG(e.salary) > (SELECT AVG(salary) FROM employees);",
    },
    {
        id: 101,
        title: "Rising Temperature (Subquery)",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 197 · Amazon · Goldman Sachs] Write a query to find all dates where the temperature was higher than the previous day in the same city. Use a correlated subquery approach.\n\nTable: weather\n\nDate-based correlated subquery — classic FAANG problem testing date arithmetic.",
        hint: "Compare each row's temperature with the temperature from the previous day using a correlated subquery.",
        solution: "SELECT w1.id FROM weather w1 WHERE w1.temperature > (SELECT w2.temperature FROM weather w2 WHERE w2.city = w1.city AND DATE(w2.date) = DATE(w1.date, '-1 day'));",
    },
    {
        id: 102,
        title: "Top 3 Orders per Customer",
        category: "Subqueries",
        difficulty: "hard",
        description: "[Amazon · Uber] Write a query to find the top 3 highest-value orders for each customer. Show customer_id, order_id, and amount.\n\nTable: orders\n\nTop-N per group without window functions — one of the hardest subquery patterns.",
        hint: "Use a correlated subquery: COUNT how many orders for the same customer have a HIGHER amount.",
        solution: "SELECT customer_id, id AS order_id, amount FROM orders o1 WHERE (SELECT COUNT(*) FROM orders o2 WHERE o2.customer_id = o1.customer_id AND o2.amount > o1.amount) < 3 ORDER BY customer_id, amount DESC;",
    },
    {
        id: 103,
        title: "Delete Duplicate Emails (Keep Min ID)",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 196 · Meta · Google] Write a SELECT query to find all duplicate email rows that should be DELETED — keep only the row with the smallest id for each email.\n\nTable: employees\n\nThis is the famous 'Delete Duplicate Emails' problem. We show the SELECT version to identify rows to delete.",
        hint: "Find rows whose id is NOT the MIN(id) for their email group.",
        solution: "SELECT * FROM employees WHERE id NOT IN (SELECT MIN(id) FROM employees GROUP BY email);",
    },
    {
        id: 104,
        title: "Managers with 5+ Direct Reports",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 570 · Amazon · Meta] Write a query to find managers who have at least 2 direct reports. Show the manager's name.\n\nTable: employees (manager_id references id)\n\nSubquery with GROUP BY + HAVING on the child side — a common organizational hierarchy question.",
        hint: "Find manager_ids that appear 2+ times, then get their names.",
        solution: "SELECT name FROM employees WHERE id IN (SELECT manager_id FROM employees WHERE manager_id IS NOT NULL GROUP BY manager_id HAVING COUNT(*) >= 2);",
    },
    {
        id: 105,
        title: "Product Price at a Given Date",
        category: "Subqueries",
        difficulty: "hard",
        description: "[LeetCode 1164 · Amazon] Write a query to find each employee's most recent salary as of '2020-12-31' from the salary history. If an employee has no salary record by that date, exclude them.\n\nTable: salaries\n\nPoint-in-time lookup using subqueries — a real-world pattern for temporal data, heavily asked at Amazon.",
        hint: "Find the MAX(from_date) for each emp_id where from_date <= '2020-12-31', then join back to get the salary.",
        solution: "SELECT s.emp_id, s.salary FROM salaries s WHERE s.from_date = (SELECT MAX(s2.from_date) FROM salaries s2 WHERE s2.emp_id = s.emp_id AND s2.from_date <= '2020-12-31');",
    },
    {
        id: 106,
        title: "Biggest Single Number",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 619] Find the largest salary that appears exactly once in the employees table. Return NULL if no single number exists.\n\nTable: employees\n\nLeetCode 619 — subquery to filter for unique values, then pick the MAX. The NULL edge case is the tricky part.",
        hint: "WHERE salary IN (SELECT salary ... HAVING COUNT = 1), then wrap in outer SELECT for NULL safety.",
        solution: "SELECT MAX(salary) AS num FROM employees WHERE salary IN (SELECT salary FROM employees GROUP BY salary HAVING COUNT(*) = 1);",
    },
    {
        id: 107,
        title: "Immediate Food Delivery II",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 1174] Find the percentage of customers whose FIRST delivery order was 'immediate' (order_date = customer_pref_delivery_date). Round to 2 decimal places.\n\nTable: delivery\n\nLeetCode 1174 — correlated subquery to find first order per customer, then apply a condition. A real e-commerce analytics pattern.",
        hint: "First find the earliest order_date per customer_id, then check if it's immediate.",
        solution: "SELECT ROUND(100.0 * SUM(CASE WHEN order_date = customer_pref_delivery_date THEN 1 ELSE 0 END) / COUNT(*), 2) AS immediate_percentage FROM delivery WHERE order_date = (SELECT MIN(d2.order_date) FROM delivery d2 WHERE d2.customer_id = delivery.customer_id);",
    },
];
