// Subqueries — 20 problems
export const subqueries = [
    {
        id: 86,
        title: "Above Average Salary",
        category: "Subqueries",
        difficulty: "easy",
        description: "Write a query to find employees whose salary is above the company average.\n\nTable: employees",
        hint: "Use a subquery: WHERE salary > (SELECT AVG(salary) ...).",
        solution: "SELECT name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);",
    },
    {
        id: 87,
        title: "Nth Highest Salary",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 177] Write a query to find the 3rd highest distinct salary.\n\nTable: employees",
        hint: "Use LIMIT 1 OFFSET 2 on DISTINCT ordered salaries.",
        solution: "SELECT DISTINCT salary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 2;",
    },
    {
        id: 88,
        title: "Employees in Largest Department",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find all employees who work in the department with the most employees.\n\nTable: employees",
        hint: "First find department_id with max count, then filter.",
        solution: "SELECT * FROM employees WHERE department_id = (SELECT department_id FROM employees GROUP BY department_id ORDER BY COUNT(*) DESC LIMIT 1);",
    },
    {
        id: 89,
        title: "Products More Expensive Than Average",
        category: "Subqueries",
        difficulty: "easy",
        description: "Write a query to find products priced higher than the average product price.\n\nTable: products",
        hint: "WHERE price > (SELECT AVG(price) ...).",
        solution: "SELECT name, price FROM products WHERE price > (SELECT AVG(price) FROM products) ORDER BY price DESC;",
    },
    {
        id: 90,
        title: "Customers with Above Average Spending",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find customers whose total spending exceeds the average customer spending.\n\nTables: orders, customers",
        hint: "Nest: calc total per customer → calc average of totals → filter.",
        solution: "SELECT c.name, SUM(o.amount) AS total_spent FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'completed' GROUP BY c.id HAVING SUM(o.amount) > (SELECT AVG(customer_total) FROM (SELECT SUM(amount) AS customer_total FROM orders WHERE status = 'completed' GROUP BY customer_id));",
    },
    {
        id: 91,
        title: "Department with Highest Average Salary",
        category: "Subqueries",
        difficulty: "medium",
        description: "Find the department name that has the highest average salary.\n\nTables: employees, departments",
        hint: "Subquery for max avg, then match.",
        solution: "SELECT d.name, ROUND(AVG(e.salary), 2) AS avg_salary FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id ORDER BY avg_salary DESC LIMIT 1;",
    },
    {
        id: 92,
        title: "Employees Earning Department Maximum",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find employees who earn the highest salary in their department.\n\nTable: employees",
        hint: "Correlated subquery: salary = (SELECT MAX(salary) ... WHERE dept matches).",
        solution: "SELECT name, salary, department_id FROM employees e WHERE salary = (SELECT MAX(salary) FROM employees e2 WHERE e2.department_id = e.department_id);",
    },
    {
        id: 93,
        title: "EXISTS Example",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find departments that have at least one employee earning more than 90000.\n\nTables: departments, employees",
        hint: "Use EXISTS with a correlated subquery.",
        solution: "SELECT d.name FROM departments d WHERE EXISTS (SELECT 1 FROM employees e WHERE e.department_id = d.id AND e.salary > 90000);",
    },
    {
        id: 94,
        title: "NOT EXISTS Example",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find products that have never been ordered using NOT EXISTS.\n\nTables: products, orders",
        hint: "NOT EXISTS (SELECT 1 FROM orders WHERE product_id = p.id).",
        solution: "SELECT name FROM products p WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.product_id = p.id);",
    },
    {
        id: 95,
        title: "Scalar Subquery",
        category: "Subqueries",
        difficulty: "easy",
        description: "Write a query to show each employee's name, salary, and the overall average salary side by side.\n\nTable: employees",
        hint: "Use a subquery in SELECT: (SELECT AVG(salary) ...).",
        solution: "SELECT name, salary, (SELECT ROUND(AVG(salary), 2) FROM employees) AS company_avg FROM employees;",
    },
    {
        id: 96,
        title: "IN with Subquery",
        category: "Subqueries",
        difficulty: "easy",
        description: "Write a query to find employees who work in departments located in 'New York' or 'Seattle'.\n\nTables: employees, departments",
        hint: "Use IN (SELECT id FROM departments WHERE location IN ...).",
        solution: "SELECT name, department_id FROM employees WHERE department_id IN (SELECT id FROM departments WHERE location IN ('New York', 'Seattle'));",
    },
    {
        id: 97,
        title: "Correlated Subquery — Salary Rank",
        category: "Subqueries",
        difficulty: "hard",
        description: "Write a query to show each employee's name, salary, and the count of employees who earn more than them.\n\nTable: employees",
        hint: "Correlated: (SELECT COUNT(*) FROM employees e2 WHERE e2.salary > e.salary).",
        solution: "SELECT name, salary, (SELECT COUNT(*) FROM employees e2 WHERE e2.salary > e.salary) AS higher_earners FROM employees ORDER BY salary DESC;",
    },
    {
        id: 98,
        title: "Customers Who Bought Everything",
        category: "Subqueries",
        difficulty: "hard",
        description: "Write a query to find customers who have bought products from EVERY product category.\n\nTables: orders, products, customers",
        hint: "COUNT(DISTINCT category) should equal total categories.",
        solution: "SELECT c.name FROM customers c JOIN orders o ON c.id = o.customer_id JOIN products p ON o.product_id = p.id GROUP BY c.id HAVING COUNT(DISTINCT p.category) = (SELECT COUNT(DISTINCT category) FROM products);",
    },
    {
        id: 99,
        title: "Second Most Recent Order",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find the second most recent order for each customer.\n\nTable: orders",
        hint: "Use a correlated subquery to rank orders per customer.",
        solution: "SELECT * FROM orders o1 WHERE (SELECT COUNT(*) FROM orders o2 WHERE o2.customer_id = o1.customer_id AND o2.order_date > o1.order_date) = 1;",
    },
    {
        id: 100,
        title: "Department Salary Vs Company Average",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find departments where the average salary is higher than the overall company average.\n\nTables: employees, departments",
        hint: "GROUP BY dept, HAVING AVG > (SELECT AVG(salary) from all employees).",
        solution: "SELECT d.name, ROUND(AVG(e.salary), 2) AS dept_avg FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.id HAVING AVG(e.salary) > (SELECT AVG(salary) FROM employees);",
    },
    {
        id: 101,
        title: "Employees with Same Salary",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find pairs of employees who earn the exact same salary. List each pair only once.\n\nTable: employees",
        hint: "Self join where salary matches and e1.id < e2.id.",
        solution: "SELECT e1.name AS emp1, e2.name AS emp2, e1.salary FROM employees e1 JOIN employees e2 ON e1.salary = e2.salary AND e1.id < e2.id;",
    },
    {
        id: 102,
        title: "Top 3 Orders Per Customer",
        category: "Subqueries",
        difficulty: "hard",
        description: "Write a query to find the top 3 highest value orders for each customer.\n\nTables: orders, customers",
        hint: "Use correlated subquery to count orders with higher amount.",
        solution: "SELECT c.name, o.amount, o.order_date FROM orders o JOIN customers c ON o.customer_id = c.id WHERE (SELECT COUNT(*) FROM orders o2 WHERE o2.customer_id = o.customer_id AND o2.amount > o.amount) < 3 ORDER BY c.name, o.amount DESC;",
    },
    {
        id: 103,
        title: "Most Popular Product",
        category: "Subqueries",
        difficulty: "medium",
        description: "Write a query to find the product(s) that appears in the most orders.\n\nTables: products, orders",
        hint: "Find max order count, then match products.",
        solution: "SELECT p.name, COUNT(*) AS order_count FROM products p JOIN orders o ON p.id = o.product_id GROUP BY p.id HAVING COUNT(*) = (SELECT MAX(cnt) FROM (SELECT COUNT(*) AS cnt FROM orders GROUP BY product_id));",
    },
    {
        id: 104,
        title: "Increasing Temperatures",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 197] Find all dates where the temperature was higher than the previous day (same city).\n\nTable: weather",
        hint: "Self join where dates are consecutive and temp increased.",
        solution: "SELECT w1.id, w1.city, w1.date, w1.temperature FROM weather w1 JOIN weather w2 ON w1.city = w2.city AND date(w1.date) = date(w2.date, '+1 day') WHERE w1.temperature > w2.temperature;",
    },
    {
        id: 105,
        title: "Delete Duplicate Emails",
        category: "Subqueries",
        difficulty: "medium",
        description: "[LeetCode 196] Write a query to find the employees who would be deleted to keep only one row per email (keep the one with smallest id). Don't actually delete — just SELECT the ones to remove.\n\nTable: employees",
        hint: "Find rows where id is NOT the min id for each email.",
        solution: "SELECT * FROM employees WHERE id NOT IN (SELECT MIN(id) FROM employees GROUP BY email);",
    },
];
